# Generated by Django 6.0.2 on 2026-02-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text="O'zingiz haqida qisqacha ma'lumot", null=True),
        ),
    ]
