# Generated by Django 6.0.2 on 2026-03-10 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_attendance_status_and_xp'),
        ('users', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='megaphone', max_length=40)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('target_type', models.CharField(choices=[('all', 'Barchaga'), ('users', 'Tanlangan foydalanuvchilarga'), ('cohorts', "Tanlangan cohort a'zolariga")], default='all', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohorts', models.ManyToManyField(blank=True, related_name='notification_broadcasts', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_broadcasts', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='manual_notification_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Bildirishnoma jo'natish",
                'verbose_name_plural': "Bildirishnoma jo'natishlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bell', max_length=40)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('manual', 'Manual'), ('subscription', 'Subscription'), ('system', 'System')], default='system', max_length=20)),
                ('external_key', models.CharField(blank=True, max_length=120, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'unique_together': {('recipient', 'external_key')},
            },
        ),
    ]
