# Generated by Django 6.0.2 on 2026-05-16 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notificationbroadcast_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, choices=[('work', 'Ish / karyera'), ('travel', 'Sayohat'), ('exam', 'Imtihon'), ('personal', 'Shaxsiy qiziqish'), ('other', 'Boshqa')], default='', max_length=20)),
                ('current_level', models.CharField(blank=True, choices=[('unknown', 'Bilmayman'), ('a1', "A1 — Boshlang'ich"), ('a2', 'A2 — Asosiy'), ('b1', "B1 — O'rta"), ('b2', "B2 — O'rta yuqori"), ('c1', 'C1 — Yuqori'), ('c2', 'C2 — Mukammal')], default='', max_length=10)),
                ('extra', models.JSONField(blank=True, help_text="Kelajakda qo'shimcha savollar uchun", null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding javobi',
                'verbose_name_plural': 'Onboarding javoblari',
            },
        ),
    ]
