# Generated by Django 6.0.2 on 2026-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useronboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_tone',
            field=models.CharField(choices=[('friendly', "Samimiy va do'stona"), ('formal', 'Rasmiy va professional'), ('brief', 'Qisqa va aniq'), ('detailed', 'Kengaytirilgan va tushuntiruvchi')], default='friendly', help_text='AzureAI yordamchisi javob beradigan uslub', max_length=16),
        ),
    ]
