# Generated by Django 6.0.2 on 2026-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_ai_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_model',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-3.1-pro-preview', 'Gemini 3.1 Pro'), ('gemini-3.5-flash', 'Gemini 3.5 Flash'), ('gemini-3.1-flash-lite', 'Gemini 3.1 Flash Lite')], default='gemini-2.5-flash', help_text='AzureAI javob yaratishda birinchi ishlatadigan Gemini modeli', max_length=80),
        ),
    ]
