# Generated by Django 6.0.2 on 2026-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_memory_enabled',
            field=models.BooleanField(default=True, help_text="AzureAI uzoq muddatli xotirasi yoqilganmi (o'quvchi shaxsiy faktlarni eslab qolish/foydalanishga ruxsat berishi)"),
        ),
    ]
