# Generated by Django 6.0.2 on 2026-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_ai_memory_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_web_search_effort',
            field=models.CharField(choices=[('light', "Yengil — faqat aniq so'rov bo'lsa"), ('medium', "O'rta — vaqtga oid savollarda avtomatik"), ('heavy', "Og'ir — har savolda AI o'zi qaror qiladi")], default='light', help_text='AzureAI internet qidiruvini qanchalik faol ishlatishi', max_length=16),
        ),
    ]
