# Generated by Django 6.0.2 on 2026-07-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_telegramauthsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthsession',
            name='client_key',
            field=models.CharField(blank=True, default='', help_text="Tokenni boshlagan brauzer sessiyasiga bog'lanish kaliti.", max_length=64),
        ),
        migrations.AddField(
            model_name='telegramauthsession',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramauthsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('authenticated', 'Tizimga kirdi'), ('expired', "Muddati o'tgan"), ('used', 'Ishlatilgan')], default='pending', max_length=20),
        ),
    ]
