# Generated by Django 6.0.2 on 2026-07-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_learnerstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('manual', 'Manual'), ('subscription', 'Subscription'), ('system', 'System'), ('streak', 'Streak')], default='system', max_length=20),
        ),
    ]
