# Generated by Django 6.0.2 on 2026-08-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_free_tier_model_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Bildirishnoma', 'verbose_name_plural': 'Bildirishnomalar'},
        ),
    ]
