# Generated by Django 6.0.8 on 2026-08-16 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram ulash tokeni',
                'verbose_name_plural': 'Telegram ulash tokenlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
