# Generated by Django 6.0.8 on 2026-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_skill',
            field=models.CharField(default='auto', help_text="AzureAI qaysi skill bilan javob berishi. `auto` — registr o'zi tanlaydi. Ataylab `choices` berilmagan: variantlar `SkillRegistry` dan olinadi, aks holda har yangi skill migratsiya talab qilardi.", max_length=40),
        ),
    ]
