# Generated by Django 6.0.8 on 2026-09-11 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customuser_ai_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('manual', 'Manual'), ('subscription', 'Subscription'), ('system', 'System'), ('streak', 'Streak'), ('reminder', 'Reminder')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('payment_days_before', models.CharField(default='3,1,0', help_text='Vergul bilan: 3,1,0 — uch kun, bir kun qolganda va muddat kuni. Har qiymat bitta xabar degani.', max_length=60, verbose_name="To'lov eslatmasi: necha kun oldin")),
                ('teacher_review_after_days', models.PositiveIntegerField(default=2, help_text="Topshiriq shuncha kundan beri tekshirilmagan bo'lsa eslatiladi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name="O'qituvchi eslatmasi: necha kundan keyin")),
                ('quiet_hours_start', models.PositiveIntegerField(default=22, help_text='Shu soatdan keyin eslatma Telegramga yuborilmay turadi (0-23).', validators=[django.core.validators.MaxValueValidator(23)], verbose_name='Jim soatlar: boshlanishi')),
                ('quiet_hours_end', models.PositiveIntegerField(default=8, help_text="Shu soatda kutib turgan eslatmalar yuboriladi. Boshlanish bilan teng bo'lsa jim soatlar o'chiriladi.", validators=[django.core.validators.MaxValueValidator(23)], verbose_name='Jim soatlar: tugashi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi")),
            ],
            options={
                'verbose_name': 'Eslatma sozlamasi',
                'verbose_name_plural': 'Eslatma sozlamasi',
            },
        ),
    ]
