# Generated by Django 6.0.8 on 2026-09-11 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_notification_category_remindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersettings',
            name='teacher_review_hour',
            field=models.PositiveIntegerField(default=9, help_text="Kunning qaysi soatida yuboriladi (0-23). Task har soat uyg'onadi va o'zi tekshiradi, ya'ni bu qiymatni o'zgartirish uchun worker qayta ishga tushirilmaydi.", validators=[django.core.validators.MaxValueValidator(23)], verbose_name="O'qituvchi eslatmasi: yuborish soati"),
        ),
    ]
