# Generated by Django 6.0.1 on 2026-01-22 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('courses', '0002_lesson_quiz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.batch'),
        ),
    ]
