# Generated by Django 6.0.8 on 2026-09-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeededRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seeder yaratgan yozuv',
                'verbose_name_plural': 'Seeder yaratgan yozuvlar',
                'indexes': [models.Index(fields=['model_label'], name='core_seeded_model_l_0ca8d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_id'), name='core_seededrecord_unique_target')],
            },
        ),
    ]
