# Generated by Django 6.0.8 on 2026-09-11 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('backup_stale_after_days', models.PositiveIntegerField(default=7, help_text="Shundan oshsa Control Center zaxira chirog'ini AMBER qiladi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Zaxira necha kundan keyin eskirgan hisoblanadi')),
                ('queue_age_amber_minutes', models.PositiveIntegerField(default=15, help_text="Eng qadimgi kutayotgan xabar shundan oshsa e'tibor talab qiladi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)], verbose_name='Navbat yoshi: AMBER chegarasi (daqiqa)')),
                ('queue_age_red_minutes', models.PositiveIntegerField(default=60, help_text='Eng qadimgi kutayotgan xabar shundan oshsa nosozlik deb qaraladi.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10080)], verbose_name='Navbat yoshi: RED chegarasi (daqiqa)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi")),
            ],
            options={
                'verbose_name': 'Operatsion chegaralar',
                'verbose_name_plural': 'Operatsion chegaralar',
            },
        ),
    ]
