# Generated by Django 6.0.8 on 2026-09-12 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operationalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsettings',
            name='dispatcher_dead_after_seconds',
            field=models.PositiveIntegerField(default=600, help_text="Shundan oshsa bot sekin emas, to'xtagan deb qaraladi.", validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(604800)], verbose_name='Bot belgisi: RED chegarasi (soniya)'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='dispatcher_stale_after_seconds',
            field=models.PositiveIntegerField(default=120, help_text="Bot shuncha vaqt o'zini belgilamasa e'tibor talab qiladi. Qiymat yozuv oralig'idan ikki baravar past bo'lsa, probe avtomatik oshiradi — aks holda chiroq doim sariq bo'lib turardi.", validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)], verbose_name='Bot belgisi: AMBER chegarasi (soniya)'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='handler_error_amber_percent',
            field=models.PositiveIntegerField(default=5, help_text="Oynadagi xato ulushi. Kamida 20 ta update bo'lmaguncha rang o'zgarmaydi — bittadan bitta xato 100% bo'lib ko'rinmasligi uchun.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Xato foizi: AMBER chegarasi (%)'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='handler_error_red_percent',
            field=models.PositiveIntegerField(default=20, help_text='Oynadagi xato ulushi shundan oshsa nosozlik deb qaraladi.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Xato foizi: RED chegarasi (%)'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='handler_latency_amber_ms',
            field=models.PositiveIntegerField(default=1500, help_text='Oynadagi p95 shundan oshsa bot sekinlashgan hisoblanadi.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(60000)], verbose_name='Javob vaqti: AMBER chegarasi (ms)'),
        ),
        migrations.AddField(
            model_name='operationalsettings',
            name='handler_latency_red_ms',
            field=models.PositiveIntegerField(default=4000, help_text='Telegram tugma bosilganda bu qadar kutish uzilish bilan teng.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(120000)], verbose_name='Javob vaqti: RED chegarasi (ms)'),
        ),
    ]
