# Generated by Django 6.0.8 on 2026-09-12 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operationalsettings_dispatcher_dead_after_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsettings',
            name='backup_retention_days',
            field=models.PositiveIntegerField(default=14, help_text="`manage.py prune_backups` shundan eski zaxiralarni o'chiradi. Rotatsiyasiz disk to'ladi va buni zaxirasiz qolganingizda bilib qolasiz. Qiymat kichik bo'lsa tiklanadigan nuqtalar kamayadi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='Zaxira necha kun saqlanadi'),
        ),
    ]
