# Generated by Django 6.0.8 on 2026-10-10 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_operationalsettings_exam_receipt_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('base_version', models.PositiveBigIntegerField(default=0)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('value', models.JSONField()),
                ('kind', models.CharField(choices=[('factory', 'Asl'), ('publish', 'Nashr'), ('rollback', 'Qaytish')], max_length=12)),
                ('reason', models.CharField(max_length=240)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.designversion')),
            ],
            options={
                'ordering': ('-number',),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DesignOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('operation', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('command', models.CharField(max_length=20)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('actor', 'operation'), name='core_design_operation_owner')],
            },
        ),
        migrations.CreateModel(
            name='DesignPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_key', models.CharField(editable=False, max_length=180)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('owner', 'name_key'), name='core_design_preset_name')],
            },
        ),
        migrations.CreateModel(
            name='DesignState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.designversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_design_singleton')],
            },
        ),
    ]
