# Generated by Django 6.0.1 on 2026-01-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('block_type', models.CharField(choices=[('HERO', 'Hero'), ('FEATURES', 'Features'), ('CURRICULUM', 'Curriculum'), ('PRICING', 'Pricing'), ('REVIEWS', 'Reviews'), ('COURSE_FEED', 'Course Feed')], max_length=50)),
                ('content_html', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AzureLMS', max_length=200)),
                ('announcement', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
