# Generated by Django 6.0.1 on 2026-01-18 21:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='content_html',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
