# Generated by Django 6.0.1 on 2026-01-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_alter_pageblock_content_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageblock",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="landing/blocks/"),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="cta_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="style_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pageblock",
            name="countdown_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="logo_dark",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="logo_light",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
        migrations.CreateModel(
            name="LeadCapture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("source", models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="MenuLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80)),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("site", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="menu_links", to="landing.siteconfig")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
