# Generated by Django 6.0.1 on 2026-01-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_expand_landing_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('HERO', 'Hero'), ('MARKETING', 'Marketing'), ('FEATURES', 'Features'), ('CURRICULUM', 'Curriculum'), ('PRICING', 'Pricing'), ('REVIEWS', 'Reviews'), ('LEAD_FORM', 'Lead Form'), ('COURSE_FEED', 'Course Feed'), ('HTML', 'HTML')], max_length=50),
        ),
    ]
