# Generated by Django 6.0.2 on 2026-07-05 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0012_paymentreceipt_base_amount_and_more'),
        ('subscriptions', '0004_seed_default_subscription_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPlanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_limit_5h', models.PositiveIntegerField(verbose_name='5 soatlik token limiti')),
                ('token_limit_weekly', models.PositiveIntegerField(verbose_name='Haftalik token limiti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_policy', to='subscriptions.plan', verbose_name='Tarif')),
            ],
            options={
                'verbose_name': 'AI tarif siyosati',
                'verbose_name_plural': 'AI tarif siyosatlari',
                'ordering': ['plan__order', 'plan__price'],
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('enforcement_enabled', models.BooleanField(default=True, help_text="O'chirilsa hech kim bloklanmaydi (chiqarish/sinov rejimi).", verbose_name='Limitlar yoqilganmi')),
                ('exempt_staff', models.BooleanField(default=True, help_text='Staff/superuser AI limitiga tushmasin.', verbose_name='Xodimlar limitdan ozod')),
                ('default_5h_token_limit', models.PositiveIntegerField(default=100000, verbose_name='Default 5 soatlik token limiti')),
                ('default_weekly_token_limit', models.PositiveIntegerField(default=1000000, verbose_name='Default haftalik token limiti')),
                ('default_model', models.CharField(blank=True, default='', help_text="Bo'sh bo'lsa settings.py qiymati ishlatiladi.", max_length=80, verbose_name='Default AI modeli')),
                ('default_effort', models.CharField(blank=True, default='', max_length=20, verbose_name='Default web-search effort')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kim yangiladi')),
            ],
            options={
                'verbose_name': 'AI sozlamasi',
                'verbose_name_plural': 'AI sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='AIUsageResetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('all', 'Hammaga (ommaviy)'), ('cohort', 'Guruh (kohort)'), ('plan', 'Tarif')], max_length=10, verbose_name="Ko'lam")),
                ('kind', models.CharField(choices=[('reset', "Reset (usage'ni nolga)"), ('bonus', "Bonus (qo'shimcha token)")], default='reset', max_length=10, verbose_name='Turi')),
                ('window', models.CharField(choices=[('5h', '5 soatlik'), ('weekly', 'Haftalik'), ('both', 'Ikkalasi')], default='both', max_length=10, verbose_name='Oyna')),
                ('bonus_tokens', models.PositiveIntegerField(default=0, verbose_name='Bonus token (kind=bonus)')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Sabab (bayram/event)')),
                ('affected_count', models.PositiveIntegerField(default=0, verbose_name="Ta'sirlangan foydalanuvchilar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reset_events', to='cohorts.cohort', verbose_name='Guruh (scope=cohort)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reset_events', to=settings.AUTH_USER_MODEL, verbose_name='Kim berdi')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_reset_events', to='subscriptions.plan', verbose_name='Tarif (scope=plan)')),
            ],
            options={
                'verbose_name': 'AI reset/bonus amali',
                'verbose_name_plural': 'AI reset/bonus amallari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUserAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_5h_token_limit', models.PositiveIntegerField(blank=True, help_text="Bo'sh bo'lsa tarif/global default ishlatiladi.", null=True, verbose_name='Shaxsiy 5 soatlik limit')),
                ('override_weekly_token_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Shaxsiy haftalik limit')),
                ('reset_5h_at', models.DateTimeField(blank=True, null=True, verbose_name='5 soatlik reset vaqti')),
                ('reset_weekly_at', models.DateTimeField(blank=True, null=True, verbose_name='Haftalik reset vaqti')),
                ('bonus_5h_tokens', models.PositiveIntegerField(default=0, verbose_name='5 soatlik bonus token')),
                ('bonus_weekly_tokens', models.PositiveIntegerField(default=0, verbose_name='Haftalik bonus token')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='AI bloklangan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_allowance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI foydalanuvchi ruxsati',
                'verbose_name_plural': 'AI foydalanuvchi ruxsatlari',
            },
        ),
    ]
