# Generated by Django 6.0.2 on 2026-08-13 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontrol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISupplyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('circuit_open_until', models.DateTimeField(blank=True, null=True)),
                ('circuit_reason', models.CharField(blank=True, default='', max_length=120)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI supply holati',
                'verbose_name_plural': 'AI supply holati',
            },
        ),
        migrations.AddField(
            model_name='aisettings',
            name='guest_demo_enabled',
            field=models.BooleanField(default=False, help_text="Default o'chiq: guest call ham global Gemini supply budgetini sarflaydi.", verbose_name='Telegram guest AI demo yoqilganmi'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='heavy_search_enabled',
            field=models.BooleanField(default=False, help_text="Free-tier rejimida default o'chiq.", verbose_name='Heavy web-search rejimi yoqilganmi'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='supply_cooldown_seconds',
            field=models.PositiveIntegerField(default=3600, verbose_name='429/quota circuit cooldown (soniya)'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='supply_daily_request_limit',
            field=models.PositiveIntegerField(default=100, help_text='Google quota raqami emas; owner belgilaydigan ichki hard budget.', verbose_name='Kunlik global provider request limiti'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='supply_minute_request_limit',
            field=models.PositiveIntegerField(default=10, help_text='Burst/fan-outni cheklaydigan owner ichki hard budgeti.', verbose_name='Bir daqiqalik global provider request limiti'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='supply_daily_token_limit',
            field=models.PositiveIntegerField(default=250000, help_text='Usage kelmasa konservativ reservation estimate hisoblanadi.', verbose_name='Kunlik global token limiti'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='supply_default_reservation_tokens',
            field=models.PositiveIntegerField(default=4000, verbose_name="Usage noma'lum call uchun token reservi"),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='supply_enforcement_enabled',
            field=models.BooleanField(default=True, help_text="Provider chaqirig'idan oldin project-wide request/token budgetni tekshiradi.", verbose_name='Global AI supply budget yoqilganmi'),
        ),
        migrations.CreateModel(
            name='AISupplyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.CharField(max_length=180, unique=True)),
                ('bucket_date', models.DateField(db_index=True)),
                ('call_type', models.CharField(choices=[('chat', 'Chat'), ('web_search', 'Web grounding/search'), ('smart_form', 'Smart Form extractor'), ('bot_guest', 'Telegram guest demo'), ('rag_embedding', 'RAG embedding'), ('memory_embedding', 'Memory embedding'), ('reindex', 'Reindex embedding'), ('other', 'Boshqa')], default='other', max_length=24)),
                ('provider', models.CharField(default='gemini', max_length=32)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='reserved', max_length=16)),
                ('reserved_requests', models.PositiveIntegerField(default=1)),
                ('reserved_tokens', models.PositiveIntegerField(default=0)),
                ('actual_requests', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('accounted_requests', models.PositiveIntegerField(default=0)),
                ('accounted_tokens', models.PositiveIntegerField(default=0)),
                ('error_kind', models.CharField(blank=True, default='', max_length=40)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_supply_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI supply hodisasi',
                'verbose_name_plural': 'AI supply hodisalari',
                'indexes': [models.Index(fields=['bucket_date', 'status'], name='aicontrol_a_bucket__1065ab_idx'), models.Index(fields=['call_type', 'bucket_date'], name='aicontrol_a_call_ty_e45385_idx'), models.Index(fields=['provider', 'bucket_date'], name='aicontrol_a_provide_d7efdf_idx')],
            },
        ),
    ]
