# Generated by Django 6.0.2 on 2026-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontrol', '0002_ai_supply_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='ai_remote_calls_enabled',
            field=models.BooleanField(default=True, help_text="O'chirilsa hech qanday remote AI chaqirig'i ketmaydi — chat, grounding, SmartForm, bot demo va embedding ham. Budjet sozlamalaridan mustaqil: bu shoshilinch to'xtatish tugmasi.", verbose_name='AI remote chaqiruvlari yoqilganmi (kill switch)'),
        ),
    ]
