# Generated by Django 6.0.2 on 2026-08-15 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontrol', '0003_aisettings_ai_remote_calls_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, help_text='Nuqta bilan ajratilgan kod, masalan `ai.kill_switch.disable`.', max_length=80)),
                ('source', models.CharField(choices=[('web', 'Web'), ('bot', 'Telegram bot'), ('worker', 'Worker'), ('cli', 'CLI'), ('release', 'Release')], default='web', max_length=10)),
                ('outcome', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failure', 'Xato'), ('denied', 'Rad etildi')], db_index=True, default='success', max_length=10)),
                ('actor_label', models.CharField(blank=True, default='', max_length=150)),
                ('target_type', models.CharField(blank=True, default='', max_length=80)),
                ('target_id', models.CharField(blank=True, default='', max_length=80)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('release_sha', models.CharField(blank=True, default='', max_length=40)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
            ],
            options={
                'verbose_name': 'Tizim audit yozuvi',
                'verbose_name_plural': 'Tizim audit yozuvlari',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='aicontrol_s_action_fb1a61_idx'), models.Index(fields=['target_type', 'target_id'], name='aicontrol_s_target__194672_idx')],
            },
        ),
    ]
