# Generated by Django 6.0.8 on 2026-08-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontrol', '0004_systemauditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Worker nomi')),
                ('last_seen_at', models.DateTimeField(verbose_name='Oxirgi belgi')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha")),
            ],
            options={
                'verbose_name': 'Worker heartbeat',
                'verbose_name_plural': 'Worker heartbeatlar',
                'ordering': ['name'],
            },
        ),
    ]
