# Generated by Django 6.0.8 on 2026-08-17 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontrol', '0005_workerheartbeat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(max_length=40, unique=True, verbose_name='Commit SHA')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(verbose_name="Oxirgi ko'rilgan")),
                ('migrations_applied', models.PositiveIntegerField(default=0, verbose_name="Qo'llangan migratsiya")),
                ('unapplied_migrations', models.JSONField(blank=True, default=list, verbose_name="Qo'llanmagan migratsiya")),
                ('gate_results', models.JSONField(blank=True, default=dict, verbose_name='Gate natijalari')),
                ('decision', models.CharField(choices=[('pending', 'Qaror kutilmoqda'), ('go', 'Ochildi'), ('hold', "To'xtatildi"), ('rolled_back', 'Qaytarildi')], default='pending', max_length=16, verbose_name='Owner qarori')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Release yozuvi',
                'verbose_name_plural': 'Release yozuvlari',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
