# Generated by Django 6.0.8 on 2026-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicontrol', '0007_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gemini', max_length=32)),
                ('model_name', models.CharField(max_length=80)),
                ('input_per_million', models.DecimalField(decimal_places=6, max_digits=12)),
                ('output_per_million', models.DecimalField(decimal_places=6, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_from', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI model narxi',
                'verbose_name_plural': 'AI model narxlari',
                'ordering': ('-effective_from', 'model_name'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_name', 'effective_from'), name='unique_price_per_model_and_date')],
            },
        ),
    ]
