"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import importlib.util
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    value = os.getenv(name, "")
    if not value.strip():
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def env_positive_int(name, default):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    try:
        parsed = int(value)
    except ValueError:
        return default
    return parsed if parsed > 0 else default


def module_available(module_name):
    return importlib.util.find_spec(module_name) is not None


# Load base env, then environment-specific file.
load_dotenv(BASE_DIR / ".env")
_raw_env = os.getenv("APP_ENV", "").strip().lower()
if not _raw_env:
    _raw_env = "local"
APP_ENV = _raw_env
IS_LOCAL = APP_ENV == "local"
LOCAL_USE_REMOTE_SERVICES = env_bool("LOCAL_USE_REMOTE_SERVICES", False)
ENV_FILE = BASE_DIR / f".env.{APP_ENV}"
SKIP_ENV_FILE = env_bool("AZURELMS_SKIP_ENV_FILE", False)
if ENV_FILE.exists() and not SKIP_ENV_FILE:
    load_dotenv(ENV_FILE, override=True)
    LOCAL_USE_REMOTE_SERVICES = env_bool("LOCAL_USE_REMOTE_SERVICES", LOCAL_USE_REMOTE_SERVICES)

_prometheus_requested = env_bool("PROMETHEUS_ENABLED", False)
PROMETHEUS_ENABLED = _prometheus_requested and module_available("django_prometheus")
if _prometheus_requested and not PROMETHEUS_ENABLED:
    print("Warning: PROMETHEUS_ENABLED is set, but django_prometheus is not installed.")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
AI_FREE_TIER_MODE = env_bool("AI_FREE_TIER_MODE", True)
# Google API Free Standard tier'da Search/Maps grounding mavjud emas. Free
# mode yoqilganida env xato qilib true berilgan taqdirda ham grounding qat'iy
# o'chiq qoladi. Paid/re-admitted rejimda esa alohida flag bilan boshqariladi.
GEMINI_GROUNDING_ENABLED = (
    not AI_FREE_TIER_MODE
    and env_bool("GEMINI_GROUNDING_ENABLED", True)
)
GEMINI_FREE_MODEL_ALLOWLIST = env_list(
    "GEMINI_FREE_MODEL_ALLOWLIST",
    ["gemini-3.1-flash-lite", "gemini-2.5-flash-lite"],
)
GEMINI_PRIMARY_MODEL = (
    os.getenv("GEMINI_PRIMARY_MODEL", "gemini-3.1-flash-lite").strip()
    or "gemini-3.1-flash-lite"
)
GEMINI_FALLBACK_MODEL = (
    os.getenv("GEMINI_FALLBACK_MODEL", "gemini-2.5-flash-lite").strip()
    or "gemini-2.5-flash-lite"
)
GEMINI_MAX_OUTPUT_TOKENS = env_positive_int("GEMINI_MAX_OUTPUT_TOKENS", 640)
GEMINI_MAX_PROMPT_CHARS = env_positive_int("GEMINI_MAX_PROMPT_CHARS", 12000)
GEMINI_REQUEST_TIMEOUT_MS = env_positive_int("GEMINI_REQUEST_TIMEOUT_MS", 8000)
GEMINI_DEADLINE_MS = env_positive_int("GEMINI_DEADLINE_MS", 20000)
GEMINI_EMBEDDING_TIMEOUT_MS = env_positive_int("GEMINI_EMBEDDING_TIMEOUT_MS", 8000)
GEMINI_EMBEDDING_MAX_INPUTS = env_positive_int("GEMINI_EMBEDDING_MAX_INPUTS", 64)
GEMINI_EMBEDDING_MAX_INPUT_CHARS = env_positive_int(
    "GEMINI_EMBEDDING_MAX_INPUT_CHARS",
    8000,
)
GEMINI_EMBEDDING_MAX_BATCH_CHARS = env_positive_int(
    "GEMINI_EMBEDDING_MAX_BATCH_CHARS",
    64000,
)

# DigitalOcean inference kodi saqlanadi, ammo owner uni alohida admission
# qilmaguncha provider factory undan foydalanmaydi.
AI_ALLOW_DIGITALOCEAN = env_bool("AI_ALLOW_DIGITALOCEAN", False)
DIGITALOCEAN_INFERENCE_API_KEY = os.getenv("DIGITALOCEAN_INFERENCE_API_KEY")
DIGITALOCEAN_INFERENCE_BASE_URL = os.getenv(
    "DIGITALOCEAN_INFERENCE_BASE_URL",
    "https://inference.do-ai.run/v1",
).rstrip("/")
DIGITALOCEAN_INFERENCE_MODEL = os.getenv("DIGITALOCEAN_INFERENCE_MODEL", "router:general")
AI_CHAT_PROVIDER = os.getenv("AI_CHAT_PROVIDER", "gemini").strip().lower()
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
BOT_USERNAME = os.getenv("BOT_USERNAME", "AzureLMS_bot")
# Bo'sh default ataylab: known-default secret bilan webhook ochiq qolmasin.
# Secret berilmasa webhook fail-closed bo'ladi (bot/views.py'da tekshiriladi).
TELEGRAM_WEBHOOK_SECRET = os.getenv("TELEGRAM_WEBHOOK_SECRET", "").strip()
TELEGRAM_MODE = os.getenv("TELEGRAM_MODE", "polling" if APP_ENV == "local" else "webhook").strip().lower()
TELEGRAM_ALLOW_INSECURE_LOCAL_WEBHOOK = env_bool("TELEGRAM_ALLOW_INSECURE_LOCAL_WEBHOOK", False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if IS_LOCAL:
        SECRET_KEY = "azurelms-local-development-insecure-secret-key"
    else:
        raise ImproperlyConfigured("SECRET_KEY must be set outside local development.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", IS_LOCAL)
ENABLE_LEGACY_ADMIN = env_bool("ENABLE_LEGACY_ADMIN", False)

# Domain sozlamalari
APP_DOMAIN = os.getenv("APP_DOMAIN", "localhost" if IS_LOCAL else "azurelms-app-aoib9.ondigitalocean.app")
default_allowed_hosts = ["localhost", "127.0.0.1", "[::1]"]
if not IS_LOCAL:
    default_allowed_hosts.extend([APP_DOMAIN, "azurebek.me"])
else:
    default_allowed_hosts.append("*")
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default_allowed_hosts)

# CSRF xavfsizligi uchun ishonchli domenlar (bu juda muhim!)
default_csrf_trusted_origins = [
    "http://localhost",
    "http://127.0.0.1",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
if not IS_LOCAL:
    default_csrf_trusted_origins = [f"https://{APP_DOMAIN}", "https://azurebek.me"]
CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default_csrf_trusted_origins,
)

# Security settings (Enforce HTTPS in production)
SECURITY_STRICT = env_bool("SECURITY_STRICT", not IS_LOCAL)
if SECURITY_STRICT:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Telegram Web Mini Apps iframe ichida ishlaganda session/CSRF cookie'lari
# third-party cookie hisoblanadi. Production defaultlari o'zgarmaydi, ammo
# HTTPS tunnel kabi muhitlar SameSite=None ni env orqali yoqa oladi.
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", SECURITY_STRICT)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", SECURITY_STRICT)
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", "Lax")
# Production Security Headers
if SECURITY_STRICT:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'



# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    'django_ckeditor_5',
    'channels',
    'users',
    'courses',
    'cohorts',
    'messenger',
    'aicontrol',
    'gamification',
    'subscriptions',
    'frontend',
    'blog',
    'sit',
    'bot',
    'corsheaders',
    'nested_admin',
    'storages',
]

if PROMETHEUS_ENABLED:
    INSTALLED_APPS.append('django_prometheus')

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "bot.django_middleware.TelegramMiniAppFrameMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if SECURITY_STRICT:
    if module_available("csp"):
        MIDDLEWARE.insert(0, "csp.middleware.CSPMiddleware")
        CSP_DEFAULT_SRC = ("'self'",)
        CSP_SCRIPT_SRC = ("'self'", "https://cdn.jsdelivr.net", "https://www.googletagmanager.com", "https://www.google-analytics.com", "'unsafe-inline'")
        CSP_STYLE_SRC = ("'self'", "https://cdn.jsdelivr.net", "https://fonts.googleapis.com", "'unsafe-inline'")
        CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net")
        CSP_IMG_SRC = ("'self'", "data:", "https://*.digitaloceanspaces.com", "https://www.google-analytics.com")
        CSP_FRAME_SRC = ("'self'", "https://www.youtube.com", "https://player.vimeo.com")
        CSP_FRAME_ANCESTORS = ("'self'", "https://web.telegram.org", "https://*.telegram.org")
        CSP_CONNECT_SRC = ("'self'", "https://www.google-analytics.com", f"wss://{APP_DOMAIN}" if APP_DOMAIN else "ws://localhost:8000")
    else:
        print("Warning: SECURITY_STRICT is enabled, but django-csp is not installed; skipping CSP middleware.")

CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", IS_LOCAL)

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.notification_context",
                "frontend.context_processors.site_settings_context",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database configuration
DATABASE_URL = os.getenv("DATABASE_URL")
# Individual variables (Manual entry)
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT", "25060")

REMOTE_DATABASE_CONFIGURED = bool((DB_NAME and DB_USER) or DATABASE_URL)
ALLOW_REMOTE_DATABASE = (not IS_LOCAL) or LOCAL_USE_REMOTE_SERVICES

if IS_LOCAL and REMOTE_DATABASE_CONFIGURED and not LOCAL_USE_REMOTE_SERVICES:
    print("--- [SYSTEM] Local mode: external database settings ignored. Using SQLite. ---")

if IS_LOCAL and not LOCAL_USE_REMOTE_SERVICES:
    # Local development SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                # SQLite'da `select_for_update()` no-op (has_select_for_update=False),
                # shuning uchun AI supply reservation kabi read-modify-write
                # tranzaksiyalari DB darajasida ketma-ketlashtirilishi shart.
                # `BEGIN DEFERRED` bilan o'qigan tranzaksiya yozishga ko'tarilganda
                # SQLite busy_timeout'ni kutmasdan darhol "database is locked"
                # qaytaradi; `IMMEDIATE` write lockni boshida oladi va raqiblar
                # xato o'rniga navbatda kutadi.
                'transaction_mode': 'IMMEDIATE',
                'timeout': 15,
                # WAL: o'quvchilar yozuvchini bloklamaydi.
                'init_command': 'PRAGMA journal_mode=WAL;',
            },
        }
    }
    # Default test bazasi — tez (shared-cache in-memory). Ammo uning qulflash
    # semantikasi real fayl bazasidan farq qiladi (SQLITE_LOCKED, busy_timeout
    # ishlamaydi), shuning uchun haqiqiy concurrency proofi faqat fayl bazasida
    # o'tkaziladi: `AZURELMS_TEST_FILE_DB=1 python manage.py test`.
    # Fayl bazasi to'liq suite'ni ~2x sekinlashtiradi, shuning uchun default emas.
    if env_bool("AZURELMS_TEST_FILE_DB", False):
        DATABASES['default']['TEST'] = {'NAME': BASE_DIR / 'test_db.sqlite3'}
elif DB_NAME and DB_USER and ALLOW_REMOTE_DATABASE:
    # Manual individual variables provided by user
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'sslmode': 'require',
            }
        }
    }
elif DATABASE_URL and ALLOW_REMOTE_DATABASE:
    # Fallback to DATABASE_URL if available
    DATABASE_URL = DATABASE_URL.strip().strip('"').strip("'")
    candidate_start = -1
    for scheme in ["postgresql://", "postgres://"]:
        pos = DATABASE_URL.find(scheme)
        if pos != -1:
            candidate_start = pos
            break
    if candidate_start != -1:
        DATABASE_URL = DATABASE_URL[candidate_start:]
    
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    raise ImproperlyConfigured(
        "Database settings are required outside local development. "
        "For local SQLite, set APP_ENV=local and keep LOCAL_USE_REMOTE_SERVICES=False."
    )

# Cache backend (DigitalOcean Valkey/Redis)
VALKEY_URL = os.getenv('VALKEY_URL')
REDIS_URL = os.getenv('REDIS_URL')
REDIS_USER = os.getenv('REDIS_USER')
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
REDIS_COMPONENT_URL = None
if REDIS_USER and REDIS_PASSWORD and REDIS_HOST and REDIS_PORT:
    REDIS_COMPONENT_URL = f"rediss://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"

# Local muhitda production redisga tasodifiy ulanishni oldini olamiz.
REMOTE_CACHE_URL = REDIS_COMPONENT_URL or VALKEY_URL or REDIS_URL
if IS_LOCAL and not LOCAL_USE_REMOTE_SERVICES:
    CACHE_URL = None
else:
    CACHE_URL = REMOTE_CACHE_URL

if IS_LOCAL and REMOTE_CACHE_URL and not LOCAL_USE_REMOTE_SERVICES:
    print("--- [SYSTEM] Local mode: external Redis/Valkey disabled to isolate from production. ---")

if CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": CACHE_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"ssl_cert_reqs": None},
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "azurelms-default-cache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Email settings (password reset, notifications)
_email_backend_env = os.getenv("EMAIL_BACKEND", "").strip()
if _email_backend_env:
    EMAIL_BACKEND = _email_backend_env
else:
    if IS_LOCAL:
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = (
            "django.core.mail.backends.smtp.EmailBackend"
            if os.getenv("EMAIL_HOST")
            else "django.core.mail.backends.console.EmailBackend"
        )

EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@azurelms.local")


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "Asia/Tashkent").strip() or "Asia/Tashkent"

USE_I18N = True

USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'users.CustomUser'

# Auth Redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'


# Static and Media Storage configuration
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_IGNORE_MISSING_FILES = True

USE_S3 = env_bool('USE_S3', False)
if IS_LOCAL and not LOCAL_USE_REMOTE_SERVICES:
    USE_S3 = False

if USE_S3:
    # DigitalOcean Spaces (fra1 - Frankfurt) sozlamalari
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')  # https://fra1.digitaloceanspaces.com
    AWS_S3_REGION_NAME = 'fra1'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_QUERYSTRING_AUTH = False  # Ochiq URL lar uchun
    AWS_DEFAULT_ACL = 'public-read'  # Media obyektlar brauzerda ochilishi uchun public read

    # Clean CDN-style URL for media files
    _endpoint_host = AWS_S3_ENDPOINT_URL.replace('https://', '').replace('http://', '')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.{_endpoint_host}'

    STORAGES = {
        # Media fayllar uchun maxsus storage klassi
        "default": {
            "BACKEND": "core.custom_storage.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Testlar `MEDIA_ROOT` ni vaqtinchalik papkaga ko'chiradi, aks holda upload
# qiladigan testlar repo ichidagi `media/` ga fayl yozib qoldiradi.
TEST_RUNNER = 'core.test_runner.MediaIsolatedTestRunner'

# CKEditor 5 upload manzili nomi
CKEDITOR_5_UPLOAD_FILE_VIEW_NAME = "ck_editor_5_upload_file"

# CKEditor 5 uchun maxsus dizayn va tugmalar paneli (Toolbar)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', '|',
                    'insertTable', 'imageUpload', '|', 'undo', 'redo'],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'language': 'uz',
    }
}

# Channels Layer - Redis mavjud bo'lsa ishlatiladi, aks holda xotiradan foydalanadi
CHANNELS_REDIS_URL = CACHE_URL
if CHANNELS_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNELS_REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
# ==========================================
# JAZZMIN ADMIN PANEL SOZLAMALARI
# ==========================================

JAZZMIN_SETTINGS = {
    # Bosh sahifa va sarlavhalar
    "site_title": "AzureLMS Boshqaruv",
    "site_header": "AzureLMS",
    "site_brand": "AzureLMS",
    "welcome_sign": "AzureLMS Boshqaruv Paneliga Xush Kelibsiz!",
    "copyright": "AzureLMS (c) 2026",
    "custom_css": "css/jazzmin-custom.css",

    # Qidiruv qutisi (Tepada turadi, O'quvchilar va Kurslarni tez topish uchun)
    "search_model": ["users.CustomUser", "courses.Course"],

    # Ikonkalar (Chap tomondagi menyu uchun chiroyli rasmlar)
    "icons": {
        "auth": "fas fa-user-shield",
        "users": "fas fa-users",
        "users.CustomUser": "fas fa-user-graduate",
        "users.Notification": "fas fa-bell",
        "users.NotificationBroadcast": "fas fa-bullhorn",
        "courses": "fas fa-graduation-cap",
        "courses.Course": "fas fa-book-open",
        "courses.Module": "fas fa-layer-group",
        "courses.Lesson": "fas fa-play-circle",
        "courses.Assignment": "fas fa-tasks",
        "courses.AssignmentSubmission": "fas fa-inbox",
        "courses.CohortLessonRelease": "fas fa-lock-open",
        "courses.LessonProgress": "fas fa-chart-line",
        "courses.Exam": "fas fa-file-signature",
        "courses.ExamSection": "fas fa-puzzle-piece",
        "courses.ExamAttempt": "fas fa-stopwatch",
        "courses.Certificate": "fas fa-certificate",
        "courses.Quiz": "fas fa-question-circle",
        "courses.Question": "fas fa-question",
        "cohorts": "fas fa-user-friends",
        "cohorts.Cohort": "fas fa-users",
        "cohorts.Enrollment": "fas fa-id-badge",
        "cohorts.PaymentReceipt": "fas fa-receipt",
        "cohorts.Attendance": "fas fa-calendar-check",
        "subscriptions": "fas fa-gem",
        "subscriptions.Plan": "fas fa-tags",
        "messenger": "fas fa-comments",
        "messenger.ChatRoom": "fas fa-comments",
        "messenger.Message": "fas fa-comment-dots",
        "messenger.AIFeedback": "fas fa-thumbs-up",
        "messenger.LessonRAGChunk": "fas fa-brain",
        "gamification": "fas fa-trophy",
        "gamification.Level": "fas fa-signal",
        "gamification.Badge": "fas fa-award",
        "gamification.EarnedBadge": "fas fa-medal",
        "gamification.Certificate": "fas fa-certificate",
        "frontend": "fas fa-palette",
        "frontend.LandingPage": "fas fa-home",
        "frontend.AboutPage": "fas fa-info-circle",
        "frontend.Statistic": "fas fa-chart-bar",
        "frontend.Testimonial": "fas fa-comment",
        "frontend.AboutStatistic": "fas fa-chart-line",
        "frontend.TeamMember": "fas fa-user-tie",
        "frontend.SiteSettings": "fas fa-cogs",
        "frontend.LandingNavItem": "fas fa-bars",
        "frontend.AuthPageSettings": "fas fa-sign-in-alt",
        "frontend.LegalPage": "fas fa-file-contract",
        "blog": "fas fa-blog",
        "blog.BlogHomeSettings": "fas fa-sliders-h",
        "blog.BlogTag": "fas fa-tag",
        "blog.BlogPost": "fas fa-newspaper",
        "blog.BlogComment": "fas fa-comments",
        "blog.BlogCommentLike": "fas fa-heart",
        "blog.BlogPostRead": "fas fa-eye",
        "blog.BlogPostClap": "fas fa-thumbs-up",
        "bot": "fas fa-robot",
    },

    # Menyularni tartibga solish
    "order_with_respect_to": [
        "users",
        "courses",
        "cohorts",
        "subscriptions",
        "messenger",
        "gamification",
        "frontend",
        "blog",
        "bot",
        "auth",
    ],

    # UI Builder: O'zingiz sayt ichidan ranglarni o'zgartira olishingiz uchun tugma!
    "show_ui_builder": False,
}
# Ranglar va ko'rinish (Azure - havorang va zamonaviy uslubda)
JAZZMIN_UI_TWEAKS = {
    # Tepa qism - Azure (Moviy) rangda, oq yozuvlar bilan
    "navbar": "navbar-dark navbar-primary",

    # Yon menyu - To'q qora rangda
    "sidebar": "sidebar-dark-primary",

    # Asosiy mavzu (Oq fon va qora aniq yozuvlar kafolati)
    "theme": "litera",

    # Dark Mode ziddiyatini vaqtincha o'chirib turamiz
    "dark_mode_theme": None,

    # Tugmalar va aksentlar moshina rang (Primary)
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ASGI configs
ASGI_APPLICATION = "core.asgi.application"
