"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    'django_ckeditor_5',
    'users',
    'courses',
    'cohorts',
    'messenger',
    'gamification',
    'subscriptions',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL ishlatish (production uchun)
# Agar PostgreSQL o'rnatilmagan bo'lsa, SQLite ishlatiladi
_USE_POSTGRES = os.getenv('USE_POSTGRES', 'false').lower() == 'true'

if _USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'azure_lms'),
            'USER': os.getenv('DB_USER', 'azurebek'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'admin'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # Development uchun SQLite (PostgreSQL kerak emas)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'users.CustomUser'
# Media fayllar (Rasmlar, PDFlar) uchun sozlama
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor 5 upload manzili nomi
CKEDITOR_5_UPLOAD_FILE_VIEW_NAME = "ck_editor_5_upload_file"

# CKEditor 5 uchun maxsus dizayn va tugmalar paneli (Toolbar)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', '|',
                    'insertTable', 'imageUpload', '|', 'undo', 'redo'],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'language': 'uz',
    }
}
# ==========================================
# JAZZMIN ADMIN PANEL SOZLAMALARI
# ==========================================

JAZZMIN_SETTINGS = {
    # Bosh sahifa va sarlavhalar
    "site_title": "AzureLMS Boshqaruv",
    "site_header": "AzureLMS",
    "site_brand": "AzureLMS",
    "welcome_sign": "AzureLMS Boshqaruv Paneliga Xush Kelibsiz!",
    "copyright": "AzureLMS © 2026",

    # Qidiruv qutisi (Tepada turadi, O'quvchilar va Kurslarni tez topish uchun)
    "search_model": ["users.CustomUser", "courses.Course"],

    # Ikonkalar (Chap tomondagi menyu uchun chiroyli rasmlar)
    "icons": {
        "auth": "fas fa-users-cog",
        "users.CustomUser": "fas fa-user-graduate",
        "courses.Course": "fas fa-book-open",
        "courses.Exam": "fas fa-file-alt",
        "courses.Quiz": "fas fa-question-circle",
    },

    # Menyularni tartibga solish
    "order_with_respect_to": ["users", "courses", "cohorts", "gamification", "bot", "azure_ai"],

    # UI Builder: O'zingiz sayt ichidan ranglarni o'zgartira olishingiz uchun tugma!
    "show_ui_builder": True,
}

# Ranglar va ko'rinish (Azure - havorang va zamonaviy uslubda)
JAZZMIN_UI_TWEAKS = {
    # Tepa qism - Azure (Moviy) rangda, oq yozuvlar bilan
    "navbar": "navbar-dark navbar-primary",

    # Yon menyu - To'q qora rangda
    "sidebar": "sidebar-dark-primary",

    # Asosiy mavzu (Oq fon va qora aniq yozuvlar kafolati)
    "theme": "litera",

    # Dark Mode ziddiyatini vaqtincha o'chirib turamiz
    "dark_mode_theme": None,

    # Tugmalar va aksentlar moshina rang (Primary)
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}