"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', 'YOUR_BOT_TOKEN_HERE')
BOT_USERNAME = os.getenv('BOT_USERNAME', 'AzureLMS_bot')
TELEGRAM_WEBHOOK_SECRET = os.getenv('TELEGRAM_WEBHOOK_SECRET', 'YOUR_SECRET_TOKEN_HERE')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['*']

# Security settings (Enforce HTTPS in production)
if not DEBUG and (os.getenv('USE_POSTGRES', 'False') == 'True' or os.getenv('DATABASE_URL')):
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    'django_ckeditor_5',
    'channels',
    'users',
    'courses',
    'cohorts',
    'messenger',
    'gamification',
    'subscriptions',
    'frontend',
    'bot',
    'corsheaders',
    'nested_admin',
    'storages',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # Note: Adjust for strict origin checking in production.

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


import os
import dj_database_url
import logging

# Database configuration
DATABASE_URL = os.getenv('DATABASE_URL')
# Individual variables (Manual entry)
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT', '25060')

IS_LOCAL = os.getenv('LOCAL_DEV', 'false').lower() == 'true'

# --- DIAGNOSTICS LOG ---
print("--- [SYSTEM] DATABASE VARS CHECK ---")
if DB_NAME and DB_USER:
    print(f"Found Individual Vars: DB_NAME={DB_NAME}, DB_USER={DB_USER}, HOST={DB_HOST}")
elif DATABASE_URL:
    print(f"Found DATABASE_URL (Starting with: {DATABASE_URL[:15]}...)")
else:
    print("Warning: No database environment variables found!")
print("--- [SYSTEM] END CHECK ---")

if DB_NAME and DB_USER:
    # Manual individual variables provided by user
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'OPTIONS': {
                'sslmode': 'require',
            }
        }
    }
elif DATABASE_URL:
    # Fallback to DATABASE_URL if available
    DATABASE_URL = DATABASE_URL.strip().strip('"').strip("'")
    candidate_start = -1
    for scheme in ['postgresql://', 'postgres://']:
        pos = DATABASE_URL.find(scheme)
        if pos != -1:
            candidate_start = pos
            break
    if candidate_start != -1:
        DATABASE_URL = DATABASE_URL[candidate_start:]
    
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
elif not IS_LOCAL:
    # Default/Emergency production settings
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'defaultdb',
            'USER': 'doadmin',
            'PASSWORD': '',
            'HOST': '',
            'PORT': '25060',
            'OPTIONS': {
                'sslmode': 'require',
            }
        }
    }
else:
    # Local development SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'azure_lms': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = 'users.CustomUser'

# Auth Redirects
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Media fayllar (Rasmlar, PDFlar) uchun sozlama
if os.getenv('USE_S3') == 'True':
    # DigitalOcean Spaces (yoki AWS S3) sozlamalari
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL') # masalan: https://fra1.digitaloceanspaces.com
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    
    # Media fayllar S3(Spaces)ga tushadi
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor 5 upload manzili nomi
CKEDITOR_5_UPLOAD_FILE_VIEW_NAME = "ck_editor_5_upload_file"

# CKEditor 5 uchun maxsus dizayn va tugmalar paneli (Toolbar)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', '|',
                    'insertTable', 'imageUpload', '|', 'undo', 'redo'],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        'language': 'uz',
    }
}

# Channels Layer configuration (Redis for Production readiness)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')],
        },
    }
}
# ==========================================
# JAZZMIN ADMIN PANEL SOZLAMALARI
# ==========================================

JAZZMIN_SETTINGS = {
    # Bosh sahifa va sarlavhalar
    "site_title": "AzureLMS Boshqaruv",
    "site_header": "AzureLMS",
    "site_brand": "AzureLMS",
    "welcome_sign": "AzureLMS Boshqaruv Paneliga Xush Kelibsiz!",
    "copyright": "AzureLMS © 2026",

    # Qidiruv qutisi (Tepada turadi, O'quvchilar va Kurslarni tez topish uchun)
    "search_model": ["users.CustomUser", "courses.Course"],

    # Ikonkalar (Chap tomondagi menyu uchun chiroyli rasmlar)
    "icons": {
        "auth": "fas fa-users-cog",
        "users.CustomUser": "fas fa-user-graduate",
        "courses.Course": "fas fa-book-open",
        "courses.Exam": "fas fa-file-alt",
        "courses.Quiz": "fas fa-question-circle",
    },

    # Menyularni tartibga solish
    "order_with_respect_to": ["users", "courses", "cohorts", "gamification", "bot", "azure_ai"],

    # UI Builder: O'zingiz sayt ichidan ranglarni o'zgartira olishingiz uchun tugma!
    "show_ui_builder": False,
}

# Ranglar va ko'rinish (Azure - havorang va zamonaviy uslubda)
JAZZMIN_UI_TWEAKS = {
    # Tepa qism - Azure (Moviy) rangda, oq yozuvlar bilan
    "navbar": "navbar-dark navbar-primary",

    # Yon menyu - To'q qora rangda
    "sidebar": "sidebar-dark-primary",

    # Asosiy mavzu (Oq fon va qora aniq yozuvlar kafolati)
    "theme": "litera",

    # Dark Mode ziddiyatini vaqtincha o'chirib turamiz
    "dark_mode_theme": None,

    # Tugmalar va aksentlar moshina rang (Primary)
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ASGI configs
ASGI_APPLICATION = "core.asgi.application"