# Generated by Django 6.0.2 on 2026-03-15 02:02

import core.utils
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Blog tegi',
                'verbose_name_plural': 'Blog teglari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension])),
                ('cover_alt_text', models.CharField(blank=True, max_length=180)),
                ('excerpt', models.TextField(blank=True)),
                ('featured_quote', models.CharField(blank=True, max_length=220)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Maqola matni')),
                ('featured', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('clap_count', models.PositiveIntegerField(default=0, editable=False)),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag')),
            ],
            options={
                'verbose_name': 'Blog posti',
                'verbose_name_plural': 'Blog postlari',
                'ordering': ['-featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('like_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog kommenti',
                'verbose_name_plural': 'Blog kommentlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komment like',
                'verbose_name_plural': 'Komment likelari',
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_like')],
            },
        ),
        migrations.CreateModel(
            name='BlogPostClap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(max_length=120)),
                ('clap_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_claps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog qarsagi',
                'verbose_name_plural': 'Blog qarsaklari',
                'constraints': [models.UniqueConstraint(fields=('post', 'viewer_key'), name='unique_post_clap_source')],
            },
        ),
        migrations.CreateModel(
            name='BlogPostRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(max_length=120)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Blog o'qilishi",
                'verbose_name_plural': "Blog o'qilishlari",
                'constraints': [models.UniqueConstraint(fields=('post', 'viewer_key'), name='unique_post_reader')],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
    ]
