# Generated by Django 6.0.2 on 2026-03-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_kicker', models.CharField(default='Azure Journal', max_length=80)),
                ('hero_title', models.CharField(default='Fikrlar, tajribalar va chuqur maqolalar uchun professional blog maydoni', max_length=220)),
                ('hero_description', models.TextField(default="Founder notes, product yozuvlari, til o'rganish bo'yicha kuzatuvlar va shaxsiy fikrlar uchun alohida jurnal.")),
                ('search_label', models.CharField(default='Maqola qidirish', max_length=80)),
                ('search_placeholder', models.CharField(default="Mavzu, tag yoki kalit so'z", max_length=140)),
                ('carousel_kicker', models.CharField(default='Latest dispatches', max_length=80)),
                ('carousel_title', models.CharField(default='Oxirgi postlar', max_length=140)),
                ('stories_kicker', models.CharField(default='Stories', max_length=80)),
                ('stories_title', models.CharField(default='Oxirgi maqolalar', max_length=140)),
                ('stories_description', models.CharField(default="Har bir maqola cover, meta, preview va aniq o'qishga qulay kartochka bilan chiqadi.", max_length=220)),
            ],
            options={
                'verbose_name': 'Blog bosh sahifa sozlamasi',
                'verbose_name_plural': 'Blog bosh sahifa sozlamalari',
            },
        ),
    ]
