# Generated by Django 6.0.2 on 2026-07-28 21:06

import core.utils
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('category', models.CharField(max_length=80, verbose_name='Kategoriya')),
                ('excerpt', models.CharField(blank=True, max_length=320, verbose_name='Qisqa tavsif')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Maqola matni')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sit/knowledge/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension], verbose_name='Muqova rasmi')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name="Bosh sahifada ko'rsatilsin")),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Nashr etilgan')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('source_url', models.URLField(blank=True, help_text='Viza, qabul va rasmiy talablar tekshirilgan sahifa.', verbose_name='Asosiy manba')),
                ('last_verified_on', models.DateField(blank=True, null=True, verbose_name='Oxirgi tekshirilgan sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SIT bilim bazasi maqolasi',
                'verbose_name_plural': 'SIT bilim bazasi maqolalari',
                'ordering': ['order', '-published_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Universitet nomi')),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('short_name', models.CharField(help_text='Masalan: İTÜ', max_length=24, verbose_name='Qisqa nomi')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Shahar')),
                ('location_detail', models.CharField(blank=True, help_text='Masalan: İstanbul (Avrupa)', max_length=160, verbose_name='Joylashuv tafsiloti')),
                ('university_type', models.CharField(choices=[('public', 'Davlat'), ('private', 'Xususiy')], db_index=True, default='public', max_length=12, verbose_name='Universitet turi')),
                ('admission_status', models.CharField(choices=[('open', 'Qabul ochiq'), ('soon', 'Tez orada'), ('closed', 'Qabul yopiq')], db_index=True, default='closed', max_length=12, verbose_name='Qabul holati')),
                ('admission_deadline', models.DateField(blank=True, null=True, verbose_name='Qabul muddati')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name="O'quv yili")),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tashkil topgan yil')),
                ('student_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Talabalar soni')),
                ('description', models.TextField(blank=True, verbose_name="Umumiy ma'lumot")),
                ('tuition_from', models.DecimalField(blank=True, db_index=True, decimal_places=0, max_digits=12, null=True, verbose_name='Eng arzon kontrakt')),
                ('tuition_currency', models.CharField(choices=[('USD', 'AQSH dollari'), ('EUR', 'Yevro'), ('TRY', 'Turk lirasi'), ('UZS', "O'zbek so'mi")], default='USD', max_length=3, verbose_name='Kontrakt valyutasi')),
                ('application_help_enabled', models.BooleanField(default=True, verbose_name='Hujjat topshirish yordami faol')),
                ('application_help_fee', models.DecimalField(decimal_places=0, default=5000, max_digits=12, verbose_name="Yordam boshlang'ich to'lovi (so'm)")),
                ('official_website', models.URLField(blank=True, verbose_name='Rasmiy sayt')),
                ('source_url', models.URLField(blank=True, help_text='Qabul, kontrakt va dasturlar tekshirilgan rasmiy sahifa.', verbose_name="Ma'lumot manbasi")),
                ('last_verified_on', models.DateField(blank=True, null=True, verbose_name='Oxirgi tekshirilgan sana')),
                ('cover_theme', models.CharField(choices=[('azure', 'Azure'), ('violet', 'Binafsha'), ('emerald', 'Yashil'), ('ruby', 'Qizil'), ('graphite', 'Grafit')], default='azure', max_length=16, verbose_name='Muqova rangi')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sit/universities/covers/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension], verbose_name='Muqova rasmi')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='sit/universities/logos/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension], verbose_name='Universitet logosi')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name="Bosh sahifada ko'rsatilsin")),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': 'Universitetlar',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_published', 'admission_status', 'order'], name='sit_univers_is_publ_3fab17_idx'), models.Index(fields=['city', 'university_type'], name='sit_univers_city_cf0d50_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniversityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=320, verbose_name='Kerakli hujjat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='sit.university')),
            ],
            options={
                'verbose_name': 'Kerakli hujjat',
                'verbose_name_plural': 'Kerakli hujjatlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Fakultet yoki institut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='sit.university')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sit/universities/gallery/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension], verbose_name='Rasm')),
                ('video_url', models.URLField(blank=True, verbose_name='Video havolasi')),
                ('caption', models.CharField(blank=True, max_length=180, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='sit.university')),
            ],
            options={
                'verbose_name': 'Universitet media fayli',
                'verbose_name_plural': 'Universitet media fayllari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityPreparationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=80, verbose_name='Til')),
                ('duration', models.CharField(default='1 yil', max_length=40, verbose_name='Davomiylik')),
                ('tuition_fee', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Kontrakt')),
                ('tuition_currency', models.CharField(choices=[('USD', 'AQSH dollari'), ('EUR', 'Yevro'), ('TRY', 'Turk lirasi'), ('UZS', "O'zbek so'mi")], default='USD', max_length=3, verbose_name='Valyuta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_courses', to='sit.university')),
            ],
            options={
                'verbose_name': 'Til tayyorlov kursi',
                'verbose_name_plural': 'Til tayyorlov kurslari',
                'ordering': ['order', 'language'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name="Yo'nalish")),
                ('degree_level', models.CharField(choices=[('associate', 'Texnikum'), ('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('phd', 'PhD')], db_index=True, max_length=16, verbose_name='Daraja')),
                ('language', models.CharField(choices=[('tr', 'Turk tili'), ('en', 'Ingliz tili'), ('other', 'Boshqa')], db_index=True, max_length=8, verbose_name="Ta'lim tili")),
                ('duration', models.CharField(help_text='Masalan: 4 yil', max_length=40, verbose_name='Davomiylik')),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Yillik kontrakt')),
                ('tuition_currency', models.CharField(choices=[('USD', 'AQSH dollari'), ('EUR', 'Yevro'), ('TRY', 'Turk lirasi'), ('UZS', "O'zbek so'mi")], default='USD', max_length=3, verbose_name='Valyuta')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='sit.universityfaculty')),
            ],
            options={
                'verbose_name': 'Universitet dasturi',
                'verbose_name_plural': 'Universitet dasturlari',
                'ordering': ['degree_level', 'faculty__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=320, verbose_name='Qabul talabi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='sit.university')),
            ],
            options={
                'verbose_name': 'Qabul talabi',
                'verbose_name_plural': 'Qabul talablari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UniversityServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=320, verbose_name='Yordam xizmati bandi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='sit.university')),
            ],
            options={
                'verbose_name': 'Yordam xizmati bandi',
                'verbose_name_plural': 'Yordam xizmati bandlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Sarlavha')),
                ('category', models.CharField(choices=[('admission', 'Qabul'), ('discount', 'Chegirma'), ('deadline', 'Muddat'), ('news', 'Yangilik')], default='news', max_length=16)),
                ('published_on', models.DateField(db_index=True, verbose_name="E'lon sanasi")),
                ('external_url', models.URLField(blank=True, verbose_name='Tashqi havola')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Nashr etilgan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='sit.university')),
            ],
            options={
                'verbose_name': "SIT e'loni",
                'verbose_name_plural': "SIT e'lonlari",
                'ordering': ['order', '-published_on', '-id'],
                'indexes': [models.Index(fields=['is_published', 'published_on'], name='sit_announc_is_publ_db5707_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='universityfaculty',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='sit_unique_university_faculty'),
        ),
        migrations.AddConstraint(
            model_name='universitypreparationcourse',
            constraint=models.UniqueConstraint(fields=('university', 'language'), name='sit_unique_preparation_language'),
        ),
        migrations.AddIndex(
            model_name='universityprogram',
            index=models.Index(fields=['degree_level', 'language', 'is_active'], name='sit_univers_degree__9fd19e_idx'),
        ),
        migrations.AddConstraint(
            model_name='universityprogram',
            constraint=models.UniqueConstraint(fields=('faculty', 'name', 'degree_level', 'language'), name='sit_unique_program_variant'),
        ),
    ]
