# Generated by Django 6.0.1 on 2026-01-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="assignment_text",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("is_present", models.BooleanField(default=True)),
                ("xp_awarded", models.PositiveIntegerField(default=0)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="education.enrollment")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("enrollment", "date")},
        ),
    ]
