# Generated by Django 6.0.2 on 2026-03-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_start', models.CharField(default="Sifatli ta'lim orqali", max_length=100, verbose_name='Sarlavha boshi')),
                ('hero_title_highlight', models.CharField(default='maqsad sari', max_length=100, verbose_name='Sarlavha ajratilgan qismi')),
                ('hero_subtitle', models.TextField(default="AzureLMS — turk tilini zamonaviy, interaktiv va qulay usulda o'rganishni xohlovchilar uchun...", verbose_name='Kichik matn (Subtitle)')),
                ('mission_title', models.CharField(default='Bizning maqsadimiz (Missiya)', max_length=200, verbose_name='Missiya Sarlavhasi')),
                ('mission_text', models.TextField(blank=True, verbose_name='Missiya matni')),
                ('vision_title', models.CharField(default='Bizning qarashimiz (Vision)', max_length=200, verbose_name='Vision Sarlavhasi')),
                ('vision_text', models.TextField(blank=True, verbose_name='Vision matni')),
            ],
            options={
                'verbose_name': 'Biz haqimizda sozlamasi',
                'verbose_name_plural': '4. Biz haqimizda sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='AboutStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Qiymati')),
                ('label', models.CharField(max_length=100, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Biz haqimizda statistikasi',
                'verbose_name_plural': '5. Biz haqimizda statistikalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='2026 yilning eng yaxshi platformasi', max_length=100, verbose_name='Bosh sahifa nishonchasi (Badge)')),
                ('hero_title_start', models.CharField(default='Turk tilini', max_length=100, verbose_name='Sarlavha boshi')),
                ('hero_title_highlight', models.CharField(default='professional', max_length=100, verbose_name='Sarlavha ajratilgan qismi')),
                ('hero_title_end', models.CharField(default="darajada o'rganing", max_length=100, verbose_name='Sarlavha oxiri')),
                ('hero_subtitle', models.TextField(default="Tajribali o'qituvchilar, interaktiv darslar va sertifikatlar bilan turk tilini A1 dan C1 gacha o'rganing.", verbose_name='Kichik matn (Subtitle)')),
                ('cta_title', models.CharField(default="Bugun o'rganishni boshlang!", max_length=100, verbose_name='Bottom CTA Sarlavhasi')),
                ('cta_description', models.TextField(default="Minglab o'quvchilar safiga qo'shiling va turk tilini professional darajada o'rganing.", verbose_name='Bottom CTA matni')),
            ],
            options={
                'verbose_name': 'Bosh sahifa sozlamasi',
                'verbose_name_plural': '1. Bosh sahifa sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Masalan: 5,000+', max_length=50, verbose_name='Qiymati')),
                ('label', models.CharField(help_text="Masalan: Faol o'quvchilar", max_length=100, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Bosh sahifa statistikasi',
                'verbose_name_plural': '2. Bosh sahifa statistikalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism-familiya')),
                ('role_1', models.CharField(max_length=100, verbose_name="Asosiy rol (Masalan: O'qituvchi)")),
                ('role_2', models.CharField(max_length=100, verbose_name="Qo'shimcha rol (Masalan: CEO)")),
                ('bio', models.TextField(verbose_name="Qisqa ma'lumot")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "6. Jamoa a'zolari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism-familiya')),
                ('role', models.CharField(default='Talaba', max_length=100, verbose_name='Kasbi/Darajasi')),
                ('text', models.TextField(verbose_name='Fikr matni')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Fikr',
                'verbose_name_plural': "3. O'quvchilar fikrlari",
            },
        ),
    ]
