# Generated by Django 6.0.2 on 2026-03-02 00:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Missiya matni'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Vision matni'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Qisqa ma'lumot"),
        ),
    ]
