# Generated by Django 6.0.2 on 2026-03-02 00:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_aboutpage_mission_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(default="AzureLMS — turk tilini zamonaviy, interaktiv va qulay usulda o'rganishni xohlovchilar uchun...", verbose_name='Kichik matn (Subtitle)'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='cta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default="Minglab o'quvchilar safiga qo'shiling va turk tilini professional darajada o'rganing.", verbose_name='Bottom CTA matni'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='hero_subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(default="Tajribali o'qituvchilar, interaktiv darslar va sertifikatlar bilan turk tilini A1 dan C1 gacha o'rganing.", verbose_name='Kichik matn (Subtitle)'),
        ),
    ]
