# Generated by Django 6.0.2 on 2026-03-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_aboutpage_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/', verbose_name='Asosiy rasm (Hero Image)'),
        ),
    ]
