# Generated by Django 6.0.2 on 2026-03-10 23:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_landingpage_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('faq', 'FAQ')], max_length=20, unique=True, verbose_name='Sahifa turi')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Kontent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Huquqiy sahifa',
                'verbose_name_plural': '8. Huquqiy sahifalar',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField(default="Professional o'qituvchilar bilan turk tilini samarali o'rganing. A1 dan C1 gacha barcha darajalar.", verbose_name='Kompaniya qisqacha matni')),
                ('contact_phone', models.CharField(default='+998 90 123 45 67', max_length=50, verbose_name='Telefon')),
                ('contact_email', models.EmailField(default='info@azurelms.uz', max_length=254, verbose_name='Email')),
                ('contact_address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('support_url', models.URLField(blank=True, verbose_name="Qo'llab-quvvatlash havolasi")),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Platforma sozlamasi',
                'verbose_name_plural': '7. Platforma sozlamalari',
            },
        ),
    ]
