# Generated by Django 6.0.2 on 2026-03-12 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_legalpage_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='hero_video',
            field=models.FileField(blank=True, help_text="MP4, WebM, OGV yoki MOV fayl yuklang. Video bo'lsa, hero qismida rasm o'rniga video ko'rsatiladi.", null=True, upload_to='landing/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'mov'])], verbose_name='Asosiy video (Hero Video)'),
        ),
    ]
