# Generated by Django 6.0.2 on 2026-03-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_landingpage_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_background_image',
            field=models.ImageField(blank=True, help_text='Ushbu rasm shaffof overlay bilan "Qanday ishlaydi?" bo\'limi orqasida chiqadi.', null=True, upload_to='landing/sections/', verbose_name='"Qanday ishlaydi?" bo\'limi foni'),
        ),
    ]
