# Generated by Django 6.0.2 on 2026-03-12 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_landingpage_how_it_works_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_background_video',
            field=models.FileField(blank=True, help_text="MP4, WebM, OGV yoki MOV yuklang. Video bo'lsa, shu bo'limda rasm o'rniga video ishlatiladi.", null=True, upload_to='landing/sections/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'mov'])], verbose_name='"Qanday ishlaydi?" bo\'limi fon videosi'),
        ),
    ]
