# Generated by Django 6.0.2 on 2026-03-12 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_landingpage_how_it_works_background_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='footer_background_image',
            field=models.ImageField(blank=True, help_text="Footer orqasida transparency overlay bilan ko'rinadigan rasm.", null=True, upload_to='landing/footer/', verbose_name='Footer fon rasmi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_background_video',
            field=models.FileField(blank=True, help_text="MP4, WebM, OGV yoki MOV yuklang. Video bo'lsa, footerda rasm o'rniga video ishlatiladi.", null=True, upload_to='landing/footer/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'mov'])], verbose_name='Footer fon videosi'),
        ),
    ]
