# Generated by Django 6.0.2 on 2026-03-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_landingpage_footer_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_visual_kicker', models.CharField(default='Welcome Back', max_length=80, verbose_name='Login kicker')),
                ('login_visual_title', models.CharField(default='Kurslaringiz, progress va bildirishnomalaringiz bir joyda kutib turibdi.', max_length=220, verbose_name='Login chap panel sarlavhasi')),
                ('login_visual_description', models.TextField(default="Tez va fokuslangan login oqimi bilan platformaga qayting. Keraksiz menyular yo'q, faqat kirish va davom etish.", verbose_name='Login chap panel matni')),
                ('login_panel_badge', models.CharField(default='Login', max_length=60, verbose_name='Login form badge')),
                ('login_panel_heading', models.CharField(default='Hisobga kirish', max_length=120, verbose_name='Login form sarlavhasi')),
                ('login_panel_intro', models.CharField(default='Email yoki username va parolingizni kiriting.', max_length=180, verbose_name='Login form izohi')),
                ('login_footer_prompt', models.CharField(default="Hali hisobingiz yo'qmi?", max_length=120, verbose_name='Login pastki matni')),
                ('login_footer_link_label', models.CharField(default="Ro'yxatdan o'ting", max_length=60, verbose_name='Login pastki link nomi')),
                ('register_visual_kicker', models.CharField(default='Create Account', max_length=80, verbose_name='Register kicker')),
                ('register_visual_title', models.CharField(default="Yangi o'quvchi safarini chiroyli, tushunarli va ishonchli onboarding bilan boshlang.", max_length=220, verbose_name='Register chap panel sarlavhasi')),
                ('register_visual_description', models.TextField(default="Hisob yaratish bir necha maydondan iborat, lekin layout tez to'ldirishga moslangan. Mobil va desktopda bir xil silliq ishlaydi.", verbose_name='Register chap panel matni')),
                ('register_panel_badge', models.CharField(default='Sign Up', max_length=60, verbose_name='Register form badge')),
                ('register_panel_heading', models.CharField(default='Hisob yaratish', max_length=120, verbose_name='Register form sarlavhasi')),
                ('register_panel_intro', models.CharField(default="Asosiy ma'lumotlarni to'ldiring va platformaga qo'shiling.", max_length=180, verbose_name='Register form izohi')),
                ('register_footer_prompt', models.CharField(default='Allaqachon hisobingiz bormi?', max_length=120, verbose_name='Register pastki matni')),
                ('register_footer_link_label', models.CharField(default='Kirish', max_length=60, verbose_name='Register pastki link nomi')),
            ],
            options={
                'verbose_name': 'Auth sahifa sozlamasi',
                'verbose_name_plural': '9. Auth sahifa sozlamalari',
            },
        ),
    ]
