# Generated by Django 6.0.2 on 2026-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_authpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='authpagesettings',
            name='help_link_label',
            field=models.CharField(default="Qo'llab-quvvatlash", max_length=60, verbose_name='Pastki yordam link nomi'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='help_prompt',
            field=models.CharField(default='Need help?', max_length=60, verbose_name='Pastki yordam matni'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='meta_description',
            field=models.CharField(default='AzureLMS hisobga kirish va xavfsiz autentifikatsiya sahifalari.', max_length=180, verbose_name='Auth meta description'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='stat_one_label',
            field=models.CharField(default='Platform access', max_length=60, verbose_name="Stat 1 yorlig'i"),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='stat_one_value',
            field=models.CharField(default='24/7', max_length=30, verbose_name='Stat 1 qiymati'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='stat_three_label',
            field=models.CharField(default='Guided journey', max_length=60, verbose_name="Stat 3 yorlig'i"),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='stat_three_value',
            field=models.CharField(default='Pro', max_length=30, verbose_name='Stat 3 qiymati'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='stat_two_label',
            field=models.CharField(default='Structured learning', max_length=60, verbose_name="Stat 2 yorlig'i"),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='stat_two_value',
            field=models.CharField(default='A1-C1', max_length=30, verbose_name='Stat 2 qiymati'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='topbar_back_label',
            field=models.CharField(default='Bosh sahifaga qaytish', max_length=90, verbose_name='Yuqoridagi qaytish tugmasi'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='visual_point_one',
            field=models.CharField(default="Yengil, fokuslangan va keraksiz chalg'ituvchisiz auth tajribasi.", max_length=180, verbose_name='Chap panel 1-matn'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='visual_point_three',
            field=models.CharField(default='Tez kirish va mobilga mos professional layout.', max_length=180, verbose_name='Chap panel 3-matn'),
        ),
        migrations.AddField(
            model_name='authpagesettings',
            name='visual_point_two',
            field=models.CharField(default='Xavfsiz parol oqimlari va tiklash scenariylari.', max_length=180, verbose_name='Chap panel 2-matn'),
        ),
    ]
