# Generated by Django 6.0.2 on 2026-03-15 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_authpagesettings_help_link_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text="Butun hero bo'limi orqasida ko'rinadigan rasm. Bo'sh qoldirilsa default nozik gradient ishlaydi.", null=True, upload_to='landing/hero/backgrounds/', verbose_name='Hero fon rasmi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_background_video',
            field=models.FileField(blank=True, help_text="MP4, WebM, OGV yoki MOV yuklang. Video bo'lsa fon rasmidan ustun turadi, bo'sh bo'lsa default gradient ishlaydi.", null=True, upload_to='landing/hero/backgrounds/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'mov'])], verbose_name='Hero fon videosi'),
        ),
    ]
