# Generated by Django 6.0.2 on 2026-03-15 03:24

from django.db import migrations, models


def create_default_nav_items(apps, schema_editor):
    LandingNavItem = apps.get_model('frontend', 'LandingNavItem')
    defaults = [
        ('home', "Bosh sahifa", 1),
        ('courses', "Kurslar", 2),
        ('pricing', "Narxlar", 3),
        ('about', "Biz haqimizda", 4),
        ('blog', "Blog", 5),
    ]
    for key, label, order in defaults:
        LandingNavItem.objects.update_or_create(
            key=key,
            defaults={
                'label': label,
                'is_visible': True,
                'order': order,
            },
        )


def delete_default_nav_items(apps, schema_editor):
    LandingNavItem = apps.get_model('frontend', 'LandingNavItem')
    LandingNavItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_landingpage_hero_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home', 'Bosh sahifa'), ('courses', 'Kurslar'), ('pricing', 'Narxlar'), ('about', 'Biz haqimizda'), ('blog', 'Blog')], max_length=20, unique=True, verbose_name='Link turi')),
                ('label', models.CharField(max_length=80, verbose_name='Navbar matni')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Landing navbar linki',
                'verbose_name_plural': '9. Landing navbar linklari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='authpagesettings',
            options={'verbose_name': 'Auth sahifa sozlamasi', 'verbose_name_plural': '10. Auth sahifa sozlamalari'},
        ),
        migrations.RunPython(create_default_nav_items, delete_default_nav_items),
    ]
