# Generated by Django 6.0.2 on 2026-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_landingnavitem_alter_authpagesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_holder',
            field=models.CharField(default='Azizbek Sirojiddinov', max_length=120, verbose_name='Karta egasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_number',
            field=models.CharField(default='8600 1234 5678 9012', max_length=32, verbose_name="To'lov karta raqami"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_instruction',
            field=models.CharField(default="To'lovni ushbu kartaga o'tkazing va chekni aniq ko'rinadigan formatda yuklang.", max_length=255, verbose_name="To'lov bo'yicha izoh"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_provider_label',
            field=models.CharField(default='Uzcard / Humo', max_length=120, verbose_name="To'lov turi yoki bank"),
        ),
    ]
