# Generated by Django 6.0.2 on 2026-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_sitesettings_payment_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_four_description',
            field=models.CharField(default='Kursni tugatib, sertifikat oling', max_length=220, verbose_name='4-qadam tavsifi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_four_title',
            field=models.CharField(default='Sertifikat oling', max_length=120, verbose_name='4-qadam sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_one_description',
            field=models.CharField(default='Bepul hisob yarating va platformaga kiring', max_length=220, verbose_name='1-qadam tavsifi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_one_title',
            field=models.CharField(default="Ro'yxatdan o'ting", max_length=120, verbose_name='1-qadam sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_three_description',
            field=models.CharField(default="Video darslar va mashqlar bilan o'rganing", max_length=220, verbose_name='3-qadam tavsifi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_three_title',
            field=models.CharField(default="O'rganishni boshlang", max_length=120, verbose_name='3-qadam sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_two_description',
            field=models.CharField(default='Darajangizga mos kursni tanlang', max_length=220, verbose_name='2-qadam tavsifi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_step_two_title',
            field=models.CharField(default='Kurs tanlang', max_length=120, verbose_name='2-qadam sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_subtitle',
            field=models.CharField(default="4 ta oddiy qadamda o'rganishni boshlang", max_length=220, verbose_name='"Qanday ishlaydi?" ostsarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='how_it_works_title',
            field=models.CharField(default='Qanday ishlaydi?', max_length=120, verbose_name='"Qanday ishlaydi?" sarlavhasi'),
        ),
    ]
