# Generated by Django 6.0.2 on 2026-05-16 16:39

import django.db.models.deletion
from django.db import migrations, models


def seed_public_admin_content(apps, schema_editor):
    LandingHeroSlide = apps.get_model('frontend', 'LandingHeroSlide')
    LandingHeroSlideMetric = apps.get_model('frontend', 'LandingHeroSlideMetric')
    LandingPortalTab = apps.get_model('frontend', 'LandingPortalTab')
    LandingPortalListItem = apps.get_model('frontend', 'LandingPortalListItem')
    LandingProcessStep = apps.get_model('frontend', 'LandingProcessStep')
    LandingNavItem = apps.get_model('frontend', 'LandingNavItem')

    if not LandingHeroSlide.objects.exists():
        slides = [
            {
                "order": 1,
                "layout": "stage_left",
                "gradient_preset": "ocean",
                "chart_preset": "academic",
                "kicker": "Turk tili platformasi",
                "title": "Akademik ruhdagi, lekin amaliy o'quv portali",
                "subtitle": "Kurs katalogi, sertifikat yo'li va o'quv muhitini bitta landing ichida tartibli ko'rsatish.",
                "primary_label": "Kurslarni ko'rish",
                "primary_url": "/courses/",
                "secondary_label": "Platforma haqida",
                "secondary_url": "/about/",
                "poster_kicker": "Academic bulletin",
                "poster_year_label": "2026",
                "poster_title": "A1-C1",
                "poster_text": "Tartibli track, lesson workspace va dashboard bitta oqimda.",
                "poster_chip_one": "A1-C1 flow",
                "poster_chip_two": "Sertifikat track",
                "poster_chip_three": "Live support",
                "side_label": "TR",
                "side_title": "A1-C1",
                "side_text": "Turk tili, dashboard va exam flow yagona tizimda.",
                "metrics": [
                    ("6 track", "A1 dan C1 gacha"),
                    ("10 hafta", "Lesson, exam va chat"),
                    ("Doimiy support", "Telegram va dashboard"),
                ],
            },
            {
                "order": 2,
                "layout": "stage_right",
                "gradient_preset": "graphite",
                "chart_preset": "catalog",
                "kicker": "Kurs arxitekturasi",
                "title": "Katalogdan lesson workspacegacha bir xil tartib",
                "subtitle": "Kurs preview, modul ritmi va qaysi yo'l bilan sertifikatga borish aniq ko'rinadi.",
                "primary_label": "Katalogni ochish",
                "primary_url": "/courses/",
                "secondary_label": "Yo'l xaritasi",
                "secondary_url": "/about/",
                "poster_kicker": "Course catalog",
                "poster_year_label": "2026",
                "poster_title": "Modul",
                "poster_text": "Har modul uchun aniq lesson ritmi, material va progress oqimi.",
                "poster_chip_one": "Modul katalogi",
                "poster_chip_two": "Weekly rhythm",
                "poster_chip_three": "Study roadmap",
                "side_label": "B2",
                "side_title": "Track",
                "side_text": "Katalog, lesson plan va student dashboard bir-biriga bog'langan.",
                "metrics": [
                    ("18-24 dars", "Har kurs uchun aniq ritm"),
                    ("Weekly plan", "Modul va homework oqimi"),
                    ("Lesson workspace", "Video, chat va exam"),
                ],
            },
            {
                "order": 3,
                "layout": "stage_left",
                "gradient_preset": "ruby",
                "chart_preset": "certification",
                "kicker": "Sertifikat yo'li",
                "title": "Imtihon va sertifikatni bir tizimda yuritish",
                "subtitle": "Exam workspace, verification va final certificate status bitta tizimda yuradi.",
                "primary_label": "Sertifikat yo'li",
                "primary_url": "/users/register/",
                "secondary_label": "Yordam markazi",
                "secondary_url": "/faq/",
                "poster_kicker": "Certification flow",
                "poster_year_label": "2026",
                "poster_title": "Final",
                "poster_text": "Imtihon, tasdiqlash va sertifikat chiqarish bitta aniq yo'lda.",
                "poster_chip_one": "Exam workspace",
                "poster_chip_two": "Certificate ready",
                "poster_chip_three": "Admin review",
                "side_label": "Live",
                "side_title": "Support",
                "side_text": "Telegram, mentor va help center bilan doimiy aloqa mavjud.",
                "metrics": [
                    ("Exam flow", "Secure workspace"),
                    ("Verification", "Admin va status"),
                    ("Ready output", "Certificate va history"),
                ],
            },
        ]
        for slide_data in slides:
            metrics = slide_data.pop("metrics")
            slide = LandingHeroSlide.objects.create(**slide_data)
            for index, (value, label) in enumerate(metrics, start=1):
                LandingHeroSlideMetric.objects.create(slide=slide, value=value, label=label, order=index)

    if not LandingPortalTab.objects.exists():
        LandingPortalTab.objects.bulk_create([
            LandingPortalTab(label="Lisans", url="/courses/", is_active=True, order=1),
            LandingPortalTab(label="Yuqori daraja", url="/courses/", order=2),
            LandingPortalTab(label="Sertifikat", url="/about/", order=3),
        ])

    if not LandingPortalListItem.objects.exists():
        LandingPortalListItem.objects.bulk_create([
            LandingPortalListItem(text="Mashhur kurslar va modul ritmi", order=1),
            LandingPortalListItem(text="Qanday ishlaydi (4 qadam)", order=2),
            LandingPortalListItem(text="O'quvchilar fikri va statistika", order=3),
            LandingPortalListItem(text="Sertifikat va qabul yo'li", order=4),
        ])

    if not LandingProcessStep.objects.exists():
        LandingProcessStep.objects.bulk_create([
            LandingProcessStep(title="Ro'yxatdan o'ting", description="Hisob ochib, qaysi darajadan boshlashingizni tanlaysiz.", icon_class="bi bi-person-plus", order=1),
            LandingProcessStep(title="Yo'lni ko'ring", description="Kurs, modul va sertifikat oqimi sizga aniq ko'rinadi.", icon_class="bi bi-signpost-split", color_class="step-number--secondary", order=2),
            LandingProcessStep(title="O'rganishni boshlang", description="Lesson workspace, chat va dashboard bitta ritmda ishlaydi.", icon_class="bi bi-play-circle", color_class="step-number--success", order=3),
            LandingProcessStep(title="Sertifikat oling", description="Track tugagach imtihon va tasdiqlash oqimiga o'tasiz.", icon_class="bi bi-patch-check", color_class="step-number--danger", order=4),
        ])

    nav_defaults = {
        "utility": [
            ("home", "Bosh sahifa", "", 1),
            ("courses", "Kurslar", "", 2),
            ("pricing", "Narxlar", "", 3),
            ("blog", "Blog", "", 4),
            ("faq", "Yordam", "", 5),
        ],
        "footer_platform": [
            ("courses", "Kurslar", "", 1),
            ("pricing", "Narxlar", "", 2),
            ("about", "Sertifikatlar", "", 3),
            ("register", "Qabul yo'li", "", 4),
        ],
        "footer_company": [
            ("about", "Biz haqimizda", "", 1),
            ("blog", "Blog", "", 2),
            ("faq", "Yordam markazi", "", 3),
        ],
        "footer_legal": [
            ("custom", "Foydalanish shartlari", "/terms-of-service/", 1),
            ("custom", "Maxfiylik siyosati", "/privacy-policy/", 2),
            ("faq", "FAQ", "", 3),
        ],
    }
    for placement, items in nav_defaults.items():
        if not LandingNavItem.objects.filter(placement=placement).exists():
            LandingNavItem.objects.bulk_create([
                LandingNavItem(placement=placement, key=key, label=label, custom_url=custom_url, order=order)
                for key, label, custom_url, order in items
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_landingpage_how_it_works_step_four_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('layout', models.CharField(choices=[('stage_left', "Vizual chapda, matn o'ngda"), ('stage_right', "Matn chapda, vizual o'ngda")], default='stage_left', max_length=20, verbose_name='Joylashuv')),
                ('gradient_preset', models.CharField(choices=[('ocean', 'Ocean teal'), ('graphite', 'Graphite blue'), ('aurora', 'Aurora violet'), ('emerald', 'Emerald gold'), ('ruby', 'Ruby night'), ('indigo', 'Indigo sky')], default='ocean', max_length=20, verbose_name='Background gradient')),
                ('chart_preset', models.CharField(choices=[('academic', 'Academic'), ('catalog', 'Catalog'), ('certification', 'Certification'), ('growth', 'Growth')], default='academic', max_length=20, verbose_name='Chart turi')),
                ('kicker', models.CharField(default='Turk tili platformasi', max_length=100, verbose_name='Kicker')),
                ('title', models.CharField(max_length=180, verbose_name='Asosiy sarlavha')),
                ('subtitle', models.TextField(verbose_name='Subtitle')),
                ('primary_label', models.CharField(default="Kurslarni ko'rish", max_length=80, verbose_name='Asosiy tugma matni')),
                ('primary_url', models.CharField(default='/courses/', max_length=200, verbose_name='Asosiy tugma URL')),
                ('secondary_label', models.CharField(blank=True, max_length=80, verbose_name='Ikkinchi tugma matni')),
                ('secondary_url', models.CharField(blank=True, max_length=200, verbose_name='Ikkinchi tugma URL')),
                ('poster_kicker', models.CharField(default='Academic bulletin', max_length=80, verbose_name='Asosiy karta yuqori matni')),
                ('poster_year_label', models.CharField(default='2026', max_length=30, verbose_name='Asosiy karta yil/label')),
                ('poster_title', models.CharField(default='A1-C1', max_length=80, verbose_name='Asosiy karta title')),
                ('poster_text', models.CharField(default='Tartibli track, lesson workspace va dashboard bitta oqimda.', max_length=180, verbose_name='Asosiy karta matni')),
                ('poster_chip_one', models.CharField(default='A1-C1 flow', max_length=80, verbose_name='Chip 1')),
                ('poster_chip_two', models.CharField(default='Sertifikat track', max_length=80, verbose_name='Chip 2')),
                ('poster_chip_three', models.CharField(default='Live support', max_length=80, verbose_name='Chip 3')),
                ('side_label', models.CharField(default='TR', max_length=40, verbose_name='Yon karta label')),
                ('side_title', models.CharField(default='A1-C1', max_length=80, verbose_name='Yon karta title')),
                ('side_text', models.CharField(default='Turk tili, dashboard va exam flow yagona tizimda.', max_length=180, verbose_name='Yon karta matni')),
            ],
            options={
                'verbose_name': 'Carousel slide',
                'verbose_name_plural': "1.1 Carousel slide'lari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingPortalListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, verbose_name='Matn')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Portal ro'yxat elementi",
                'verbose_name_plural': "1.4 Portal ro'yxat elementlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingPortalTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Tab nomi')),
                ('url', models.CharField(default='/courses/', max_length=200, verbose_name='URL')),
                ('is_active', models.BooleanField(default=False, verbose_name="Aktiv ko'rinsinmi?")),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Portal tab',
                'verbose_name_plural': '1.3 Portal tablari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('description', models.CharField(max_length=240, verbose_name='Tavsif')),
                ('icon_class', models.CharField(default='bi bi-person-plus', help_text='Masalan: bi bi-person-plus, bi bi-signpost-split, bi bi-play-circle', max_length=60, verbose_name='Bootstrap icon class')),
                ('color_class', models.CharField(blank=True, max_length=60, verbose_name="Qo'shimcha rang class")),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Jarayon qadami',
                'verbose_name_plural': '1.5 Jarayon qadamlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='landingnavitem',
            name='custom_url',
            field=models.CharField(blank=True, help_text="Custom URL tanlansa yoki route bo'sh bo'lsa shu ishlaydi. Masalan: /courses/ yoki https://...", max_length=220, verbose_name='Custom URL'),
        ),
        migrations.AddField(
            model_name='landingnavitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Yangi tabda ochilsinmi?'),
        ),
        migrations.AddField(
            model_name='landingnavitem',
            name='placement',
            field=models.CharField(choices=[('main', 'Asosiy navbar'), ('utility', 'Yuqori utility navbar'), ('footer_platform', 'Footer: Platforma'), ('footer_company', 'Footer: Kompaniya'), ('footer_legal', 'Footer: Huquqiy')], default='main', max_length=30, verbose_name="Qayerda ko'rinsin?"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='courses_section_kicker',
            field=models.CharField(default='Katalog', max_length=80, verbose_name='Kurslar blok kicker'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='courses_section_link_label',
            field=models.CharField(default="Barcha kurslarni ko'rish", max_length=100, verbose_name='Kurslar blok linki'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='courses_section_title',
            field=models.CharField(default='Mashhur kurslar', max_length=120, verbose_name='Kurslar blok sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_kicker',
            field=models.CharField(default='Boshlash', max_length=80, verbose_name='Bottom CTA kicker'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_primary_label',
            field=models.CharField(default='Bepul boshlash', max_length=80, verbose_name='CTA asosiy tugma'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_secondary_label',
            field=models.CharField(default="Kurslarni ko'rish", max_length=80, verbose_name='CTA ikkinchi tugma'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='portal_cover_label',
            field=models.CharField(default='AzureLMS model', max_length=100, verbose_name='Portal cover label'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='portal_cover_title',
            field=models.CharField(default='TR A1-C1', max_length=80, verbose_name='Portal cover title'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='portal_media_label',
            field=models.CharField(default='Platforma preview', max_length=100, verbose_name='Portal media label'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='portal_program_title',
            field=models.CharField(default='Kurslar, lesson workspace va sertifikat oqimi bitta tizimda', max_length=180, verbose_name='Portal blok sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='process_section_kicker',
            field=models.CharField(default='Jarayon', max_length=80, verbose_name='Jarayon blok kicker'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='search_placeholder',
            field=models.CharField(default='Turk tili, B2, sertifikat yoki blog qidiring', max_length=180, verbose_name='Qidiruv placeholder'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='testimonials_section_kicker',
            field=models.CharField(default='Fikrlar', max_length=80, verbose_name='Fikrlar blok kicker'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='testimonials_section_title',
            field=models.CharField(default="O'quvchilar fikri", max_length=120, verbose_name='Fikrlar blok sarlavhasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='AzureLMS', max_length=80, verbose_name='Brend nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='brand_tagline',
            field=models.CharField(default='Turk tili va sertifikat platformasi', max_length=140, verbose_name='Brend ostsarlavhasi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Logo rasmi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_mark_text',
            field=models.CharField(default='AL', help_text="Logo rasmi yuklanmasa shu qisqa matn ko'rinadi.", max_length=8, verbose_name='Logo mark matni'),
        ),
        migrations.AlterField(
            model_name='landingnavitem',
            name='key',
            field=models.CharField(choices=[('custom', 'Custom URL'), ('home', 'Bosh sahifa'), ('courses', 'Kurslar'), ('pricing', 'Narxlar'), ('about', 'Biz haqimizda'), ('blog', 'Blog'), ('faq', 'Yordam / FAQ'), ('login', 'Kirish'), ('register', "Ro'yxatdan o'tish"), ('dashboard', 'Dashboard')], default='custom', max_length=20, verbose_name='Link turi'),
        ),
        migrations.CreateModel(
            name='LandingHeroSlideMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=70, verbose_name='Qiymat')),
                ('label', models.CharField(max_length=120, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='frontend.landingheroslide', verbose_name='Slide')),
            ],
            options={
                'verbose_name': 'Carousel slide statistikasi',
                'verbose_name_plural': '1.2 Carousel slide statistikalari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_public_admin_content, migrations.RunPython.noop),
    ]
