# Generated by Django 6.0.2 on 2026-05-16 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_public_admin_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='cta_background_image',
            field=models.ImageField(blank=True, help_text="Bottom CTA orqasida ko'rinadigan rasm. Video bo'lsa, rasm o'rniga video ishlaydi.", null=True, upload_to='landing/cta/', verbose_name='CTA fon rasmi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_background_preset',
            field=models.CharField(choices=[('midnight', 'Midnight blue'), ('ocean', 'Ocean teal'), ('graphite', 'Graphite blue'), ('aurora', 'Aurora violet'), ('emerald', 'Emerald gold'), ('ruby', 'Ruby night'), ('indigo', 'Indigo sky')], default='midnight', max_length=20, verbose_name='CTA fon preseti'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cta_background_video',
            field=models.FileField(blank=True, help_text="MP4, WebM, OGV yoki MOV yuklang. Video bo'lsa, CTA fonida rasm o'rniga ishlatiladi.", null=True, upload_to='landing/cta/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogv', 'mov'])], verbose_name='CTA fon videosi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_background_preset',
            field=models.CharField(choices=[('midnight', 'Midnight blue'), ('ocean', 'Ocean teal'), ('graphite', 'Graphite blue'), ('aurora', 'Aurora violet'), ('emerald', 'Emerald gold'), ('ruby', 'Ruby night'), ('indigo', 'Indigo sky')], default='midnight', max_length=20, verbose_name='Footer fon preseti'),
        ),
    ]
