# Generated by Django 6.0.2 on 2026-07-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_sitesettings_brand_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingAIFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, verbose_name='Xususiyat matni')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'AI xususiyati',
                'verbose_name_plural': '2.2 AI repetitor xususiyatlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingExamSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name="Ko'nikma nomi")),
                ('meta', models.CharField(default='30 MIN · 40 Q', max_length=60, verbose_name='Meta matn')),
                ('icon_class', models.CharField(default='bi bi-headphones', help_text='Masalan: bi bi-headphones, bi bi-book, bi bi-pencil, bi bi-mic', max_length=60, verbose_name='Bootstrap icon class')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Imtihon ko'nikmasi",
                'verbose_name_plural': "2.3 Imtihon ko'nikmalari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingLevelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Bosqich nomi')),
                ('description', models.CharField(max_length=140, verbose_name='Tavsif')),
                ('level_range', models.CharField(default='A1—A2', max_length=30, verbose_name="Daraja oralig'i")),
                ('lessons_count', models.CharField(default='36', max_length=20, verbose_name='Darslar soni')),
                ('duration', models.CharField(default='14 hafta', max_length=40, verbose_name='Davomiyligi')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('current', 'Joriy'), ('locked', 'Yopiq')], default='open', max_length=20, verbose_name='Holati')),
                ('status_label', models.CharField(blank=True, help_text="Bo'sh bo'lsa holat turi nomi ishlatiladi.", max_length=40, verbose_name='Holat matni')),
                ('is_visible', models.BooleanField(default=True, verbose_name="Ko'rinsinmi?")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Daraja bosqichi',
                'verbose_name_plural': "2.1 Daraja yo'li bosqichlari",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_demo_answer',
            field=models.CharField(default="gittim · gittin · gitti. Keling, uchta misol bilan mustahkamlaymiz va so'ng siz yozib ko'rasiz.", max_length=240, verbose_name='AI demo javob'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_demo_input_placeholder',
            field=models.CharField(default='Savol yozing…', max_length=80, verbose_name='AI demo input placeholder'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_demo_question',
            field=models.CharField(default='"gitmek" o\'tgan zamonda qanday bo\'ladi?', max_length=200, verbose_name='AI demo savol'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_demo_session_label',
            field=models.CharField(default='azure-ai · session', max_length=60, verbose_name="AI demo sessiya yorlig'i"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_kicker',
            field=models.CharField(default='AI repetitor', max_length=60, verbose_name="AI bo'lim kicker"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_subtitle',
            field=models.CharField(default='Azure AI sizning bosqichingizni, xatolaringizni va maqsadingizni eslab qoladi — javoblar tasodifiy emas, sizga moslangan.', max_length=240, verbose_name="AI bo'lim matni"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='ai_title',
            field=models.CharField(default='Darslaringizni biladigan shaxsiy repetitor.', max_length=140, verbose_name="AI bo'lim sarlavhasi"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_cta_label',
            field=models.CharField(default="Namuna sertifikatni ko'rish", max_length=80, verbose_name='Sertifikat CTA matni'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_kicker',
            field=models.CharField(default='Sertifikat', max_length=60, verbose_name="Sertifikat bo'lim kicker"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_course',
            field=models.CharField(default='Turk tili — C1', max_length=80, verbose_name='Namuna sertifikat kursi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_date',
            field=models.CharField(default='12.06.2026', max_length=30, verbose_name='Namuna sertifikat sanasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_label',
            field=models.CharField(default='Sertifikat', max_length=40, verbose_name="Namuna sertifikat yorlig'i"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_location',
            field=models.CharField(default='Toshkent', max_length=40, verbose_name='Namuna sertifikat joyi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_name',
            field=models.CharField(default='Nigora Soliyeva', max_length=80, verbose_name='Namuna sertifikat egasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_number',
            field=models.CharField(default='№ AZ-2026-0481', max_length=40, verbose_name='Namuna sertifikat raqami'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_sample_score',
            field=models.CharField(default='96 / 100', max_length=30, verbose_name='Namuna sertifikat bahosi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_text',
            field=models.CharField(default='Har bir sertifikat QR kod orqali tekshiriladi. Ish beruvchi yoki universitet bir soniyada haqiqiyligiga ishonch hosil qiladi.', max_length=280, verbose_name="Sertifikat bo'lim matni"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='cert_title',
            field=models.CharField(default='Tugatdingizmi — tasdiqlangan sertifikat.', max_length=140, verbose_name="Sertifikat bo'lim sarlavhasi"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_course_kicker',
            field=models.CharField(default='Joriy kurs', max_length=60, verbose_name='Demo kurs kicker'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_course_name',
            field=models.CharField(default='Turk tili — B2 Intensiv', max_length=90, verbose_name='Demo kurs nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_next_badge',
            field=models.CharField(default='KEYINGI', max_length=30, verbose_name='Demo keyingi dars nishoni'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_next_time',
            field=models.CharField(default='Bugun · 18:00', max_length=60, verbose_name='Demo keyingi dars vaqti'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_next_title',
            field=models.CharField(default='Listening — Dialog 14', max_length=90, verbose_name='Demo keyingi dars nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_progress',
            field=models.PositiveSmallIntegerField(default=68, verbose_name='Demo progress (%)'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_stat_one_label',
            field=models.CharField(default="Dars o'tildi", max_length=40, verbose_name='Demo stat 1 nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_stat_one_value',
            field=models.CharField(default='18', max_length=20, verbose_name='Demo stat 1 qiymati'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_stat_three_label',
            field=models.CharField(default='Streak', max_length=40, verbose_name='Demo stat 3 nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_stat_three_value',
            field=models.CharField(default='11', max_length=20, verbose_name='Demo stat 3 qiymati'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_stat_two_label',
            field=models.CharField(default='Exam natija', max_length=40, verbose_name='Demo stat 2 nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_stat_two_value',
            field=models.CharField(default='94%', max_length=20, verbose_name='Demo stat 2 qiymati'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='demo_url',
            field=models.CharField(default='app.azurelms.uz/dashboard', max_length=120, verbose_name='Demo URL matni'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='exam_kicker',
            field=models.CharField(default='Imtihon muhiti', max_length=60, verbose_name="Imtihon bo'lim kicker"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='exam_subtitle',
            field=models.CharField(default="Timer, bo'limlar va baholash — rasmiy imtihonga to'liq mos muhitda mashq qiling.", max_length=240, verbose_name="Imtihon bo'lim matni"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='exam_title',
            field=models.CharField(default="Haqiqiy imtihon. To'rt ko'nikma, xalqaro format.", max_length=140, verbose_name="Imtihon bo'lim sarlavhasi"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='final_cta_secondary_label',
            field=models.CharField(default='Narxlar bilan tanishish', max_length=80, verbose_name='Pastki CTA ikkinchi havola'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='final_cta_title',
            field=models.CharField(default='Bugun birinchi darsdan boshlang.', max_length=120, verbose_name='Pastki CTA sarlavhasi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_col_company_title',
            field=models.CharField(default='Kompaniya', max_length=40, verbose_name='Footer: Kompaniya ustuni nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_col_contact_title',
            field=models.CharField(default='Aloqa', max_length=40, verbose_name='Footer: Aloqa ustuni nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_col_legal_title',
            field=models.CharField(default='Huquqiy', max_length=40, verbose_name='Footer: Huquqiy ustuni nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_col_platform_title',
            field=models.CharField(default='Platforma', max_length=40, verbose_name='Footer: Platforma ustuni nomi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_copyright',
            field=models.CharField(default='© 2026 AZURELMS — BARCHA HUQUQLAR HIMOYALANGAN', max_length=140, verbose_name='Footer copyright matni'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='footer_tagline',
            field=models.CharField(default="O'zbek tilida turk tilini tartibli o'rgatadigan onlayn platforma.", max_length=160, verbose_name='Footer tavsifi'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_kicker_left',
            field=models.CharField(default='Turk tili · A1—C1 · Onlayn platforma', max_length=140, verbose_name='Hero kicker (chap)'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_kicker_right',
            field=models.CharField(default='EST. 2024', max_length=60, verbose_name="Hero kicker (o'ng)"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_primary_label',
            field=models.CharField(default='Bepul boshlash', max_length=60, verbose_name='Hero asosiy tugma matni'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='hero_secondary_label',
            field=models.CharField(default="Daraja yo'lini ko'rish", max_length=60, verbose_name='Hero ikkinchi tugma matni'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='path_kicker',
            field=models.CharField(default="Daraja yo'li", max_length=60, verbose_name="Daraja yo'li kicker"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='path_subtitle',
            field=models.CharField(default="Bo'sh joy yo'q, qaytariq yo'q — faqat keyingi aniq qadam.", max_length=200, verbose_name="Daraja yo'li ostsarlavhasi"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='path_title',
            field=models.CharField(default='Uch bosqich. Har biri oldingisiga ulanadi.', max_length=140, verbose_name="Daraja yo'li sarlavhasi"),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='rail_footer_line_one',
            field=models.CharField(default='© 2026 AZURELMS', max_length=60, verbose_name='Rail footer 1-qator'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='rail_footer_line_two',
            field=models.CharField(default='TOSHKENT · UZ', max_length=60, verbose_name='Rail footer 2-qator'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='rail_tagline',
            field=models.CharField(default='Turk tili · A1—C1', max_length=80, verbose_name='Rail tagline'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='decimals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Kasr xonalar soni'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="To'ldirilsa sahifada 0 dan shu songacha animatsiya bo'ladi. Masalan: 2400 yoki 4.9", max_digits=10, null=True, verbose_name='Raqamli qiymat (animatsiya)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='suffix',
            field=models.CharField(blank=True, help_text='Masalan: + yoki %', max_length=8, verbose_name="Qiymat qo'shimchasi"),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.CharField(blank=True, help_text="Raqamli qiymat bo'sh bo'lsa shu matn statik ko'rsatiladi. Masalan: 5,000+", max_length=50, verbose_name='Matnli qiymat'),
        ),
    ]
