# Generated by Django 6.0.2 on 2026-07-26 20:56

from django.db import migrations


def seed_landing_content(apps, schema_editor):
    LandingPage = apps.get_model("frontend", "LandingPage")
    LandingLevelStage = apps.get_model("frontend", "LandingLevelStage")
    LandingAIFeature = apps.get_model("frontend", "LandingAIFeature")
    LandingExamSkill = apps.get_model("frontend", "LandingExamSkill")
    LandingNavItem = apps.get_model("frontend", "LandingNavItem")
    Statistic = apps.get_model("frontend", "Statistic")

    # 1) Mavjud singleton'ning eski (ilgari template'da ishlatilmagan) hero
    #    maydonlarini hozir sahifada ko'rinadigan matnga moslaymiz.
    page = LandingPage.objects.first()
    if page is not None:
        page.hero_title_start = "A1 dan C1 gacha — bitta"
        page.hero_title_highlight = "aniq tizimda"
        page.hero_title_end = "."
        page.hero_subtitle = (
            "<p>Chalkash kurslar emas. Jonli darslar, AI repetitor, imtihon "
            "muhiti va tasdiqlangan sertifikat — boshidan oxirigacha tartibga "
            "solingan yagona ish maydoni.</p>"
        )
        page.save(update_fields=[
            "hero_title_start",
            "hero_title_highlight",
            "hero_title_end",
            "hero_subtitle",
        ])

    # 2) Daraja yo'li bosqichlari
    if not LandingLevelStage.objects.exists():
        LandingLevelStage.objects.bulk_create([
            LandingLevelStage(
                title="Poydevor",
                description="Alifbo · talaffuz · muloqot",
                level_range="A1—A2",
                lessons_count="36",
                duration="14 hafta",
                status="open",
                status_label="Ochiq",
                order=1,
            ),
            LandingLevelStage(
                title="Ravonlik",
                description="Grammatika · suhbat · matn",
                level_range="B1—B2",
                lessons_count="48",
                duration="18 hafta",
                status="current",
                status_label="Joriy",
                order=2,
            ),
            LandingLevelStage(
                title="Mahorat",
                description="Akademik til · imtihon",
                level_range="C1",
                lessons_count="30",
                duration="12 hafta",
                status="locked",
                status_label="Yopiq",
                order=3,
            ),
        ])

    # 3) AI repetitor xususiyatlari
    if not LandingAIFeature.objects.exists():
        LandingAIFeature.objects.bulk_create([
            LandingAIFeature(text="Darslarni o'zbek tilida tushuntiradi", order=1),
            LandingAIFeature(text="Grammatik xatolarni tuzatadi", order=2),
            LandingAIFeature(text="Speaking va writing'ni baholaydi", order=3),
            LandingAIFeature(text="Zaif mavzular bo'yicha reja tuzadi", order=4),
        ])

    # 4) Imtihon ko'nikmalari
    if not LandingExamSkill.objects.exists():
        LandingExamSkill.objects.bulk_create([
            LandingExamSkill(name="Listening", meta="30 MIN · 40 Q", icon_class="bi bi-headphones", order=1),
            LandingExamSkill(name="Reading", meta="60 MIN · 40 Q", icon_class="bi bi-book", order=2),
            LandingExamSkill(name="Writing", meta="60 MIN · 2 T", icon_class="bi bi-pencil", order=3),
            LandingExamSkill(name="Speaking", meta="15 MIN · 3 P", icon_class="bi bi-mic", order=4),
        ])

    # 5) Footer navigatsiya linklari (landing footerini bir xil ko'rsatadi,
    #    lekin admin'dan boshqariladigan qiladi). Faqat footer placement'lari
    #    bo'sh bo'lsa seed qilamiz.
    footer_placements = ["footer_platform", "footer_company", "footer_legal"]
    if not LandingNavItem.objects.filter(placement__in=footer_placements).exists():
        LandingNavItem.objects.bulk_create([
            # Platforma
            LandingNavItem(placement="footer_platform", key="courses", label="Kurslar", is_visible=True, order=1),
            LandingNavItem(placement="footer_platform", key="pricing", label="Narxlar", is_visible=True, order=2),
            LandingNavItem(placement="footer_platform", key="custom", label="AI repetitor", custom_url="#ai", is_visible=True, order=3),
            # Kompaniya
            LandingNavItem(placement="footer_company", key="about", label="Biz haqimizda", is_visible=True, order=1),
            LandingNavItem(placement="footer_company", key="blog", label="Blog", is_visible=True, order=2),
            LandingNavItem(placement="footer_company", key="faq", label="Yordam", is_visible=True, order=3),
            # Huquqiy
            LandingNavItem(placement="footer_legal", key="custom", label="Maxfiylik", custom_url="/privacy-policy/", is_visible=True, order=1),
            LandingNavItem(placement="footer_legal", key="custom", label="Shartlar", custom_url="/terms-of-service/", is_visible=True, order=2),
        ])

    # 6) Bosh sahifa statistikasi (animatsiyali)
    if not Statistic.objects.exists():
        Statistic.objects.bulk_create([
            Statistic(numeric_value=2400, suffix="+", decimals=0, label="Faol talaba", order=1),
            Statistic(numeric_value=6, suffix="", decimals=0, label="Daraja", order=2),
            Statistic(numeric_value=94, suffix="%", decimals=0, label="Sertifikat oldi", order=3),
            Statistic(numeric_value="4.9", suffix="", decimals=1, label="Reyting", order=4),
        ])


def unseed_landing_content(apps, schema_editor):
    # Reversible: faqat seed qilingan child qatorlarni olib tashlaymiz.
    # LandingPage matn maydonlari qaytarilmaydi (xavfsizroq).
    apps.get_model("frontend", "LandingLevelStage").objects.all().delete()
    apps.get_model("frontend", "LandingAIFeature").objects.all().delete()
    apps.get_model("frontend", "LandingExamSkill").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_landingaifeature_landingexamskill_landinglevelstage_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_landing_content, unseed_landing_content),
    ]
