# Generated by Django 6.0.2 on 2026-02-22 07:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Kurs nomi")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Kurs tavsifi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Dars mavzusi"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="YouTube Unlisted havolasi", null=True
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Dars qoidalari, matnlari va tushuntirishlar",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Dars tartibi"),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=10, help_text="Darsga kirgani uchun beriladigan XP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Savol matni"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="Savol bali"),
                ),
            ],
            options={
                "verbose_name": "Savol",
                "verbose_name_plural": "Savollar",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Imtihon nomi (Masalan: A1 Final)"
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("visa", "Visa (Orali'q Imtihon)"),
                            ("final", "Final (Yakuniy Imtihon)"),
                        ],
                        max_length=10,
                        verbose_name="Imtihon turi",
                    ),
                ),
                (
                    "weight_percentage",
                    models.PositiveIntegerField(
                        help_text="Umumiy bahodagi o'rni (Masalan: Visa=40, Final=60)"
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=60, help_text="O'tish uchun kerakli minimal foiz"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon",
                "verbose_name_plural": "Imtihonlar",
            },
        ),
        migrations.CreateModel(
            name="ExamSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("reading", "O'qish (Reading)"),
                            ("listening", "Eshitish (Listening)"),
                            ("writing", "Yozish (Writing)"),
                            ("speaking", "Gapirish (Speaking)"),
                            ("grammar_quiz", "Grammatika va Lug'at (Test)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="O'quvchiga shartni tushuntirish"
                    ),
                ),
                (
                    "reading_text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, null=True, verbose_name="Reading uchun matn"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="Listening uchun YouTube/Audio link",
                        null=True,
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        help_text="Ushbu bo'lim uchun beriladigan maksimal ball"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.exam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imtihon Bo'limi",
                "verbose_name_plural": "Imtihon Bo'limlari",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Vazifa nomi")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Vazifa sharti"
                    ),
                ),
                (
                    "max_xp",
                    models.PositiveIntegerField(default=50, verbose_name="Maksimal XP"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vazifa",
                "verbose_name_plural": "Vazifalar",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Modul nomi")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modul",
                "verbose_name_plural": "Modullar",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
            ),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=200, verbose_name="Variant matni"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="To'g'ri javobmi?"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="courses.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant",
                "verbose_name_plural": "Variantlar",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Quiz nomi")),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=20, help_text="To'g'ri ishlagani uchun beriladigan XP"
                    ),
                ),
                (
                    "exam_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Imtihon ichidagi test bo'lsa tanlang",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.examsection",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dars ichidagi quiz bo'lsa tanlang",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizlar",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="courses.quiz",
            ),
        ),
    ]
