# Generated by Django 6.0.1 on 2026-01-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="quiz_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="quiz_pass_score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
