# Generated by Django 6.0.2 on 2026-03-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=20, help_text='Kursning taxminiy davomiyligi (soatlarda)'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', "Boshlang'ich (A1-A2)"), ('intermediate', "O'rta (B1-B2)"), ('advanced', 'Mukammal (C1-C2)')], default='beginner', max_length=20, verbose_name='Daraja'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='courses/previews/', verbose_name='Tanishtiruv videosi'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Kurs rasmi'),
        ),
    ]
