# Generated by Django 6.0.2 on 2026-03-03 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_course_level_course_preview_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan sana')),
                ('certificate_id', models.CharField(max_length=50, unique=True, verbose_name='Sertifikat ID')),
                ('final_score', models.PositiveIntegerField(verbose_name='Yakuniy ball')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course', verbose_name='Kurs darajasi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Olingan ball (foizda, 0-100)')),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.exam', verbose_name='Imtihon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Imtihon Natijasi',
                'verbose_name_plural': 'Imtihon Natijalari',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
