# Generated by Django 6.0.2 on 2026-03-03 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_certificate_examsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsection',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Ushbu bo'limni ishlash uchun beriladigan vaqt (daqiqa)"),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.examsection'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('blur_warnings', models.PositiveIntegerField(default=0, help_text='Sahifadan chiqib ketishlar soni (Anti-Cheat)')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Olingan jami ball', max_digits=5)),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdi")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.exam', verbose_name='Imtihon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Imtihon Urinishi (Attempt)',
                'verbose_name_plural': 'Imtihon Urinishlari',
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Writing yoki ochiq savollar uchun javob', null=True)),
                ('audio_file_url', models.URLField(blank=True, help_text='Speaking yozuvi havolasi (S3/DigitalOcean)', null=True)),
                ('awarded_score', models.DecimalField(decimal_places=2, default=0, help_text="O'qituvchi qo'ygan yoki avto tekshirilgan ball", max_digits=5)),
                ('is_graded', models.BooleanField(default=False, help_text="O'qituvchi tekshirib balldan qoniqdimi?")),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='courses.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.choice')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
    ]
