# Generated by Django 6.0.2 on 2026-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_examsection_time_limit_minutes_question_exam_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kurs narxi (UZS)'),
        ),
    ]
