# Generated by Django 6.0.2 on 2026-03-12 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quizattempt_quizanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name="O'qituvchi tasdiqlaganmi?"),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='Yakuniy izoh'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name="Tekshirgan o'qituvchi"),
        ),
        migrations.CreateModel(
            name='ExamSectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Berilgan ball')),
                ('feedback', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_reviews', to='courses.examattempt', verbose_name='Imtihon urinishi')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_reviews', to='courses.examsection', verbose_name="Imtihon bo'limi")),
            ],
            options={
                'verbose_name': "Imtihon bo'limi bali",
                'verbose_name_plural': "Imtihon bo'limi ballari",
                'ordering': ['section__order'],
                'unique_together': {('attempt', 'section')},
            },
        ),
    ]
