# Generated by Django 6.0.2 on 2026-03-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_examattempt_is_reviewed_examattempt_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_mode',
            field=models.CharField(choices=[('image', 'Yuklangan rasm'), ('gradient', 'Gradient cover')], default='image', help_text='Agar rasm yuklamasangiz, tanlangan gradient preset avtomatik ishlaydi.', max_length=20, verbose_name='Cover turi'),
        ),
        migrations.AddField(
            model_name='course',
            name='gradient_cover_label',
            field=models.CharField(blank=True, help_text="Bo'sh qoldirilsa kurs darajasi ishlatiladi.", max_length=48, verbose_name='Gradient kichik badge matni'),
        ),
        migrations.AddField(
            model_name='course',
            name='gradient_cover_title',
            field=models.CharField(blank=True, help_text="Bo'sh qoldirilsa kurs nomi ishlatiladi.", max_length=80, verbose_name='Gradient markaziy yozuvi'),
        ),
        migrations.AddField(
            model_name='course',
            name='gradient_preset',
            field=models.CharField(choices=[('aurora_blush', 'Aurora Blush'), ('sky_lilac', 'Sky Lilac'), ('rose_mist', 'Rose Mist'), ('midnight_wave', 'Midnight Wave'), ('mint_halo', 'Mint Halo'), ('peach_glow', 'Peach Glow'), ('violet_satin', 'Violet Satin'), ('golden_haze', 'Golden Haze')], default='aurora_blush', max_length=40, verbose_name='Gradient preset'),
        ),
    ]
