# Generated by Django 6.0.2 on 2026-03-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_cover_mode_course_gradient_cover_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='gradient_preset',
            field=models.CharField(choices=[('aurora_blush', 'Aurora Blush'), ('sky_lilac', 'Sky Prism'), ('rose_mist', 'Rose Mist'), ('midnight_wave', 'Midnight Wave'), ('mint_halo', 'Mint Halo'), ('peach_glow', 'Peach Glow'), ('violet_satin', 'Violet Satin'), ('golden_haze', 'Golden Haze'), ('brand_horizon', 'Brand Horizon'), ('bronze_nocturne', 'Bronze Nocturne'), ('emerald_glass', 'Emerald Glass'), ('paper_sunrise', 'Paper Sunrise'), ('crimson_silk', 'Crimson Silk'), ('ice_circuit', 'Ice Circuit'), ('noir_orchid', 'Noir Orchid')], default='aurora_blush', max_length=40, verbose_name='Gradient preset'),
        ),
    ]
