# Generated by Django 6.0.2 on 2026-03-17 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_attendance_status_and_xp'),
        ('courses', '0010_alter_course_gradient_preset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Javob matni')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/submissions/%Y/%m/', verbose_name='Biriktirma')),
                ('status', models.CharField(choices=[('pending', 'Tekshiruv kutilmoqda'), ('approved', 'Tasdiqlangan'), ('needs_revision', 'Qayta ishlash kerak')], default='pending', max_length=16)),
                ('teacher_feedback', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('awarded_xp', models.PositiveIntegerField(default=0, verbose_name='Berilgan XP')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan vaqt')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name="Tekshirgan o'qituvchi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "Vazifa topshirig'i",
                'verbose_name_plural': 'Vazifa topshiriqlari',
                'ordering': ['-updated_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CohortLessonRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_released', models.BooleanField(default=True, verbose_name='Ochilganmi')),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ochilgan vaqt')),
                ('release_note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_releases', to='cohorts.cohort')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_releases', to='courses.lesson')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_lessons', to=settings.AUTH_USER_MODEL, verbose_name="Ochgan admin/o'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh dars accessi',
                'verbose_name_plural': 'Guruh dars accesslari',
                'ordering': ['lesson__module__order', 'lesson__order'],
                'unique_together': {('cohort', 'lesson')},
            },
        ),
    ]
