# Generated by Django 6.0.2 on 2026-03-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_attendance_status_and_xp'),
        ('courses', '0011_assignmentsubmission_cohortlessonrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlanganmi')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='cohorts.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Dars progressi',
                'verbose_name_plural': 'Dars progresslari',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
