# Generated by Django 6.0.2 on 2026-04-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohorts", "0008_attendance_cohorts_att_date_3b32c4_idx_and_more"),
        ("courses", "0012_lessonprogress"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["enrollment", "is_completed"],
                name="courses_les_enrollm_1a9f99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["last_accessed_at"], name="courses_les_last_ac_ff361f_idx"
            ),
        ),
    ]
