# Generated by Django 6.0.2 on 2026-04-19 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lessonprogress_courses_les_enrollm_1a9f99_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examattempt',
            options={'ordering': ['-attempt_number', '-id'], 'verbose_name': 'Imtihon Urinishi (Attempt)', 'verbose_name_plural': 'Imtihon Urinishlari'},
        ),
        migrations.AlterUniqueTogether(
            name='examattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=2, help_text="O'quvchi ushbu imtihonni maksimal necha marta topshira oladi."),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Urinish raqami'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam', '-attempt_number'], name='courses_exa_student_31895b_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'attempt_number'), name='courses_examattempt_student_exam_attempt_uniq'),
        ),
    ]
