# Generated by Django 6.0.2 on 2026-04-19 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_examattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_min_attendance_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sertifikat uchun minimal attendance (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_min_lesson_completion_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sertifikat uchun minimal lesson completion (%)'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_requires_all_assignments_approved',
            field=models.BooleanField(default=False, verbose_name='Sertifikat uchun barcha assignmentlar tasdiqlansin'),
        ),
        migrations.AddField(
            model_name='exam',
            name='minimum_attendance_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Imtihon uchun minimal attendance (%)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='minimum_lesson_completion_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Imtihon uchun minimal lesson completion (%)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='prerequisite_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_exams', to='courses.exam', verbose_name='Talab qilinadigan oldingi imtihon'),
        ),
        migrations.AddField(
            model_name='exam',
            name='requires_all_assignments_approved',
            field=models.BooleanField(default=False, verbose_name='Imtihon uchun barcha assignmentlar tasdiqlansin'),
        ),
    ]
