# Generated by Django 6.0.2 on 2026-04-19 23:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_certificate_min_attendance_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Item prompt')),
                ('short_label', models.CharField(blank=True, help_text='Masalan: 12, A yoki Blank 3', max_length=32, verbose_name='Qisqa label')),
                ('helper_text', models.CharField(blank=True, max_length=255, verbose_name='Yordamchi matn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Ball')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha item metadata")),
            ],
            options={
                'verbose_name': 'Reading item',
                'verbose_name_plural': 'Reading itemlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingAcceptedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Text tasklarda to'liq javob, matching/claim tasklarda option key yoki label yoziladi.", max_length=255, verbose_name='Qabul qilinadigan javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='courses.readingitem', verbose_name='Reading item')),
            ],
            options={
                'verbose_name': 'Qabul qilinadigan javob',
                'verbose_name_plural': 'Qabul qilinadigan javoblar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Passage sarlavhasi')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Passage matni')),
                ('paragraph_labels', models.JSONField(blank=True, default=list, help_text="Masalan: ['A', 'B', 'C']", verbose_name="Paragraf label ro'yxati")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='courses.examsection', verbose_name="Reading bo'limi")),
            ],
            options={
                'verbose_name': 'Reading passage',
                'verbose_name_plural': 'Reading passagelar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Task sarlavhasi')),
                ('task_type', models.CharField(choices=[('single_choice', 'Multiple choice (single)'), ('multiple_choice', 'Multiple choice (multi-select)'), ('true_false_not_given', 'True / False / Not Given'), ('yes_no_not_given', 'Yes / No / Not Given'), ('matching', 'Matching'), ('text_input', 'Sentence completion / short answer'), ('structured_gap_fill', 'Summary / Note / Table / Flow-chart'), ('diagram_label', 'Diagram label completion')], max_length=32, verbose_name='Task engine turi')),
                ('display_variant', models.CharField(blank=True, choices=[('', 'Default'), ('matching_information', 'Matching information'), ('matching_headings', 'Matching headings'), ('matching_features', 'Matching features'), ('matching_sentence_endings', 'Matching sentence endings'), ('sentence_completion', 'Sentence completion'), ('short_answer', 'Short-answer'), ('summary_completion', 'Summary completion'), ('note_completion', 'Note completion'), ('table_completion', 'Table completion'), ('flowchart_completion', 'Flow-chart completion'), ('diagram_labels', 'Diagram labels')], max_length=40, verbose_name="UI ko'rinishi")),
                ('instructions', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Task ko'rsatmasi")),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Summary, table yoki diagram uchun asosiy HTML/tuzilma shu yerda saqlanadi.', null=True, verbose_name='Task body / layout')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Boshlanish raqami')),
                ('question_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tugash raqami')),
                ('max_selections_per_item', models.PositiveIntegerField(default=1, verbose_name='Item uchun maksimal tanlov')),
                ('max_words_per_answer', models.PositiveIntegerField(default=0, help_text="0 bo'lsa cheklov yo'q.", verbose_name="Javobdagi maksimal so'z soni")),
                ('allow_option_reuse', models.BooleanField(default=True, verbose_name='Variantlarni qayta ishlatish mumkinmi')),
                ('allow_review_flag', models.BooleanField(default=True, verbose_name='Review flag ruxsat etilsin')),
                ('case_sensitive_grading', models.BooleanField(default=False, verbose_name='Text gradingda katta-kichik harf farqi hisobga olinsin')),
                ('punctuation_sensitive', models.BooleanField(default=False, verbose_name='Text gradingda tinish belgilari hisobga olinsin')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha task metadata")),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='courses.readingpassage', verbose_name='Passage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_tasks', to='courses.examsection', verbose_name="Reading bo'limi")),
            ],
            options={
                'verbose_name': 'Reading task',
                'verbose_name_plural': 'Reading tasklar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(blank=True, help_text='Matching yoki TF/NG tasklarda accepted answer shu key bilan solishtiriladi.', max_length=64, verbose_name='Option key')),
                ('label', models.CharField(blank=True, max_length=16, verbose_name="Ko'rinadigan label")),
                ('text', models.CharField(max_length=255, verbose_name='Variant matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_correct', models.BooleanField(default=False, help_text='Faqat item-specific choice tasklarda ishlatiladi.', verbose_name="To'g'ri javobmi")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha metadata")),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.readingitem', verbose_name='Item option')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_options', to='courses.readingtask', verbose_name='Shared option task')),
            ],
            options={
                'verbose_name': 'Reading option',
                'verbose_name_plural': 'Reading optionlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='readingitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.readingtask', verbose_name='Task'),
        ),
        migrations.CreateModel(
            name='ExamSectionAttemptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict, verbose_name='Runtime state')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_states', to='courses.examattempt', verbose_name='Imtihon urinishi')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_states', to='courses.examsection', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Imtihon bo'limi runtime state",
                'verbose_name_plural': "Imtihon bo'limi runtime statelari",
                'ordering': ['section__order', 'id'],
                'unique_together': {('attempt', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ReadingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_ids', models.JSONField(blank=True, default=list, verbose_name='Tanlangan bir nechta variant IDlari')),
                ('text_answer', models.TextField(blank=True, verbose_name='Matnli javob')),
                ('is_flagged_for_review', models.BooleanField(default=False, verbose_name='Review uchun belgilangan')),
                ('awarded_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Berilgan ball')),
                ('is_graded', models.BooleanField(default=False, verbose_name='Baholangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_responses', to='courses.examattempt', verbose_name='Imtihon urinishi')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='courses.readingitem', verbose_name='Reading item')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.readingoption', verbose_name='Tanlangan bitta variant')),
            ],
            options={
                'verbose_name': 'Reading javob',
                'verbose_name_plural': 'Reading javoblar',
                'ordering': ['item__task__order', 'item__order', 'id'],
                'indexes': [models.Index(fields=['attempt', 'item'], name='courses_rea_attempt_57a58b_idx')],
                'unique_together': {('attempt', 'item')},
            },
        ),
    ]
