# Generated by Django 6.0.2 on 2026-06-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_readingitem_readingacceptedanswer_readingpassage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_flagged_for_review',
            field=models.BooleanField(default=False, help_text="O'quvchi keyin qaytish uchun belgiladi (review flag)"),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
