# Generated by Django 6.0.2 on 2026-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_studentanswer_is_flagged_for_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsection',
            name='audio_play_limit',
            field=models.PositiveIntegerField(default=0, help_text='Listening audiosi necha marta eshitilishi mumkin. 0 = cheksiz.', verbose_name='Audio tinglash limiti'),
        ),
    ]
