# Generated by Django 6.0.2 on 2026-07-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_examsection_audio_play_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_word_count',
            field=models.PositiveIntegerField(default=0, help_text='Writing javobi uchun yuqori chegara. 0 = cheksiz.', verbose_name="Maksimal so'z soni"),
        ),
        migrations.AddField(
            model_name='question',
            name='min_word_count',
            field=models.PositiveIntegerField(default=0, help_text="Writing javobi uchun minimal so'z talabi (masalan 150). 0 = talab yo'q.", verbose_name="Minimal so'z soni"),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='grader_feedback',
            field=models.TextField(blank=True, default='', help_text="O'qituvchining shu javobga (esse/yozuv) alohida izohi"),
        ),
    ]
