# Generated by Django 6.0.2 on 2026-08-15 01:07

import core.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_question_max_word_count_question_min_word_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='audio_key',
            field=models.CharField(blank=True, default='', help_text="Private storage'dagi speaking yozuvi kaliti", max_length=255),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=core.private_storage.private_media_storage, upload_to='assignments/submissions/%Y/%m/', verbose_name='Biriktirma'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='audio_file_url',
            field=models.URLField(blank=True, help_text='Legacy: eski public havola (endi ishlatilmaydi)', null=True),
        ),
    ]
