# Generated by Django 6.0.8 on 2026-10-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_exam_review_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='review_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
