# Generated by Django 6.0.1 on 2026-01-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
