# Generated by Django 6.0.1 on 2026-01-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('DIRECT', 'Direct'), ('BOT', 'Bot')], default='GROUP', max_length=20),
        ),
    ]
