# Generated by Django 6.0.2 on 2026-03-25 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0006_cohort_telegram_chat_id_cohort_telegram_chat_title'),
        ('courses', '0012_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, verbose_name='Telegram chat ID')),
                ('chat_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram chat nomi')),
                ('attendance_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Davomat sanasi')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopilgan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='open', max_length=12)),
                ('late_after_minutes', models.PositiveIntegerField(default=15, verbose_name='Kechikish chegarasi')),
                ('attendance_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Davomat post xabar ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_telegram_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Yopgan foydalanuvchi')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_sessions', to='cohorts.cohort')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_sessions', to='courses.lesson')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_telegram_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Boshlagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Telegram dars sessiyasi',
                'verbose_name_plural': 'Telegram dars sessiyalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLessonCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(verbose_name='Telegram user ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram username')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Check-in vaqti')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_checkins', to='cohorts.enrollment', verbose_name='Enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='bot.telegramlessonsession', verbose_name='Sessiya')),
            ],
            options={
                'verbose_name': 'Telegram check-in',
                'verbose_name_plural': 'Telegram check-inlar',
                'ordering': ['checked_in_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='telegramlessonsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('chat_id',), name='unique_open_telegram_session_per_chat'),
        ),
        migrations.AlterUniqueTogether(
            name='telegramlessoncheckin',
            unique_together={('session', 'enrollment')},
        ),
    ]
