# Generated by Django 6.0.2 on 2026-07-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram user ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('demo_questions_used', models.PositiveIntegerField(default=0, verbose_name='AI demo savollar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot mehmoni',
                'verbose_name_plural': 'Bot mehmonlari',
            },
        ),
    ]
