# Generated by Django 6.0.2 on 2026-07-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botguest'),
        ('users', '0010_customuser_ai_web_search_effort'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Qabul qiluvchi Telegram ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_outbox', to='users.notification')),
            ],
            options={
                'verbose_name': 'Telegram outbox',
                'verbose_name_plural': 'Telegram outbox',
                'ordering': ['id'],
            },
        ),
    ]
