# Generated by Django 6.0.2 on 2026-07-13 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramoutbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotBroadcastDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_broadcast_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot broadcast qoralama',
                'verbose_name_plural': 'Bot broadcast qoralamalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
