# Generated by Django 6.0.2 on 2026-07-17 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botbroadcastdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assignment', 'Vazifa javobi'), ('quiz', 'Quiz')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_pending_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot kutilayotgan amal',
                'verbose_name_plural': 'Bot kutilayotgan amallar',
            },
        ),
    ]
