# Generated by Django 6.0.2 on 2026-08-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_botpendingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramoutbox',
            name='claim_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramoutbox',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], db_index=True, default='pending', max_length=10),
        ),
    ]
