# Generated by Django 6.0.8 on 2026-09-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegramoutbox_claim_token_telegramoutbox_claimed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramoutbox',
            name='failure_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='telegramoutbox',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
