# Generated by Django 6.0.8 on 2026-09-11 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegramoutbox_failure_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRuntimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('dm_batch_size', models.PositiveIntegerField(default=25, help_text='Shaxsiy xabarlar (bildirishnoma DM) uchun bir sikldagi chegara.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='DM navbati: bir siklda nechta xabar')),
                ('group_batch_size', models.PositiveIntegerField(default=10, help_text="Classbook guruh xabarlari DM'dan OLDIN olinadi, shuning uchun bu ham jonli darsdagi tezlikka bevosita ta'sir qiladi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Guruh navbati: bir siklda nechta xabar')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=15, help_text='Worker navbatni qancha vaqtda bir tekshiradi.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='Sikllar orasidagi kutish (soniya)')),
                ('lease_seconds', models.PositiveIntegerField(default=120, help_text="Worker xabarni yuborayotganda o'lib qolsa, qator shuncha vaqtdan keyin yana navbatga qaytadi. Juda qisqa qilinsa bitta xabar ikki marta ketishi ehtimoli oshadi.", validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)], verbose_name='Lease muddati (soniya)')),
                ('send_interval_ms', models.PositiveIntegerField(default=50, help_text="Telegram turli chatlarga ~30 xabar/sekund beradi. 50 ms ≈ 20/sek. Jonli darsda 429 ko'rinsa shu qiymatni oshiring. 0 — oraliqsiz (faqat test/debug uchun).", validators=[django.core.validators.MaxValueValidator(5000)], verbose_name='Yuborishlar orasidagi oraliq (millisekund)')),
                ('max_attempts', models.PositiveIntegerField(default=5, help_text="Shundan keyin xabar terminal (dead-letter) bo'ladi. 429 va noto'g'ri token urinish sarflamaydi.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Maksimal urinish soni')),
                ('base_backoff_seconds', models.PositiveIntegerField(default=30, help_text='Keyingi urinishlarda ikkilanadi: 30 → 60 → 120 → 240.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Birinchi kutish (soniya)')),
                ('max_backoff_seconds', models.PositiveIntegerField(default=900, help_text='Kutish shundan oshmaydi.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(86400)], verbose_name='Maksimal kutish (soniya)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Kim o'zgartirdi")),
            ],
            options={
                'verbose_name': 'Bot yetkazish sozlamasi',
                'verbose_name_plural': 'Bot yetkazish sozlamasi',
            },
        ),
    ]
