# Generated by Django 6.0.8 on 2026-09-12 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_botruntimesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='botruntimesettings',
            name='metrics_flush_seconds',
            field=models.PositiveIntegerField(default=30, help_text="Bot o'z holatini shuncha vaqtda bir marta yozadi. Kichik qiymat Control Center'da yangiroq raqam beradi, ammo DB'ga ko'proq yozadi. Bu qiymat chiroqning eskirish chegarasiga ham ta'sir qiladi: chegara bu oraliqdan ikki baravar past bo'lib qolmaydi.", validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)], verbose_name="Kuzatuv yozuvi oralig'i (soniya)"),
        ),
        migrations.AddField(
            model_name='botruntimesettings',
            name='metrics_window_seconds',
            field=models.PositiveIntegerField(default=300, help_text="O'rtacha va p95 shu oynadagi update'lardan hisoblanadi. Oynadan tashqaridagi o'lchov tashlanadi — aks holda uch soat oldingi sekinlik hozirgi tezlik bo'lib ko'rinardi.", validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)], verbose_name="O'lchov oynasi (soniya)"),
        ),
    ]
