# Generated by Django 6.0.8 on 2026-09-12 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_botruntimesettings_metrics_flush_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botruntimesettings',
            name='dead_letter_replay_limit',
            field=models.PositiveIntegerField(default=200, help_text="Qayta yuborish sahifasi shu qadar terminal qator ko'rsatadi va bitta amal shu qadariga tegadi. Katta qilinsa minglab xabar bir vaqtda navbatga qaytib, 429 Flood control keltirishi mumkin.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Dead-letter: bir amalda nechta qator'),
        ),
    ]
