# Generated by Django 6.0.2 on 2026-03-01 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ta'rif nomi (Masalan: Oddiy)")),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Oylik to'lov (so'm)")),
                ('description', models.TextField(help_text="Ta'rif haqida qisqacha ma'lumot", verbose_name='Qisqa izoh')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Ommabopmi?')),
                ('button_text', models.CharField(default='Boshlash', max_length=50, verbose_name='Tugma matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
            ],
            options={
                'verbose_name': "Ta'rif",
                'verbose_name_plural': "Ta'riflar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imkoniyat (Masalan: Barcha darslarga kirish)')),
                ('is_included', models.BooleanField(default=True, verbose_name='Kiritilganmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartibi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Imkoniyat',
                'verbose_name_plural': 'Imkoniyatlar',
                'ordering': ['order'],
            },
        ),
    ]
