# Generated by Django 6.0.2 on 2026-03-02 00:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Ta'rif haqida qisqacha ma'lumot", verbose_name='Qisqa izoh'),
        ),
    ]
