# Generated by Django 6.0.2 on 2026-04-19 22:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_paymentreceipt_base_amount_and_more'),
        ('courses', '0015_course_certificate_min_attendance_percent_and_more'),
        ('subscriptions', '0002_alter_plan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Campaign nomi')),
                ('description', models.TextField(blank=True, verbose_name='Qisqa tavsif')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('discount_type', models.CharField(choices=[('percent', 'Foiz (%)'), ('fixed', 'Fixed summa'), ('set_price', 'Narxni aniq summa qilish')], max_length=16, verbose_name='Chegirma turi')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chegirma qiymati')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Minimal checkout summasi')),
                ('max_total_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jami maksimal ishlatish soni')),
                ('max_redemptions_per_user', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bir user uchun maksimal ishlatish soni')),
                ('applies_to_first_purchase_only', models.BooleanField(default=False, verbose_name="Faqat birinchi to'lov uchun")),
                ('allow_on_renewals', models.BooleanField(default=True, verbose_name='Renewal checkoutlarda ham ishlasin')),
                ('allow_stacking', models.BooleanField(default=False, help_text='Hozir checkout bitta promo qabul qiladi; bu flag keyingi kengaytirish uchun saqlanadi.', verbose_name='Boshqa promo bilan birga ishlatish mumkinmi')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('internal_note', models.TextField(blank=True, verbose_name='Ichki izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_cohorts', models.ManyToManyField(blank=True, related_name='promo_campaigns', to='cohorts.cohort', verbose_name='Faqat shu cohortlar uchun')),
                ('applicable_courses', models.ManyToManyField(blank=True, related_name='promo_campaigns', to='courses.course', verbose_name='Faqat shu kurslar uchun')),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='promo_campaigns', to='subscriptions.plan', verbose_name='Faqat shu tariflar uchun')),
            ],
            options={
                'verbose_name': 'Promo campaign',
                'verbose_name_plural': 'Promo campaignlar',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Promo kod')),
                ('normalized_code', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=16)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name="Kod bo'yicha maksimal ishlatish soni")),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Kod boshlanish vaqti')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Kod tugash vaqti')),
                ('note', models.TextField(blank=True, verbose_name='Kod izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Faqat shu user uchun')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='subscriptions.promocampaign', verbose_name='Campaign')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_kind', models.CharField(choices=[('initial', 'Initial checkout'), ('renewal', 'Renewal checkout')], default='initial', max_length=16)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('applied', 'Applied'), ('released', 'Released'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='reserved', max_length=16)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Asl summa')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chegirma summasi')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yakuniy summa')),
                ('code_snapshot', models.CharField(max_length=64, verbose_name='Ishlatilgan kod snapshoti')),
                ('campaign_name_snapshot', models.CharField(max_length=180, verbose_name='Campaign snapshoti')),
                ('discount_type_snapshot', models.CharField(choices=[('percent', 'Foiz (%)'), ('fixed', 'Fixed summa'), ('set_price', 'Narxni aniq summa qilish')], max_length=16)),
                ('discount_value_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_note', models.TextField(blank=True, verbose_name='Status izohi')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='subscriptions.promocampaign', verbose_name='Campaign')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='cohorts.enrollment', verbose_name='Enrollment')),
                ('payment_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemption', to='cohorts.paymentreceipt', verbose_name="To'lov cheki")),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='subscriptions.promocode', verbose_name='Promo kod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Promo redemption',
                'verbose_name_plural': 'Promo redemptionlar',
                'ordering': ['-reserved_at', '-id'],
                'indexes': [models.Index(fields=['status', 'reserved_at'], name='subscriptio_status_cd21c7_idx'), models.Index(fields=['student', 'status'], name='subscriptio_student_c0c7d1_idx')],
            },
        ),
    ]
