# Generated by Django 6.0.2 on 2026-02-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Guruh nomi")),
                ("start_date", models.DateField(verbose_name="Boshlanish sanasi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "telegram_group_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Telegram guruh havolasi"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cohorts",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guruh",
                "verbose_name_plural": "Guruhlar",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Faol (To'lov qilingan)"),
                            ("pending", "To'lov kutilmoqda"),
                            ("expired", "Muddati tugagan (Bloklangan)"),
                            ("frozen", "Muzlatilgan"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Holati",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="So'nggi to'lov sanasi"
                    ),
                ),
                (
                    "next_payment_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Navbatdagi to'lov oxirgi muddati",
                        null=True,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="cohorts.cohort",
                        verbose_name="Guruh",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna (A'zolik)",
                "verbose_name_plural": "Obunalar",
                "unique_together": {("student", "cohort")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "is_present",
                    models.BooleanField(default=True, verbose_name="Qatnashdi"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.lesson",
                        verbose_name="Dars",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cohorts.enrollment",
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Davomat",
                "verbose_name_plural": "Davomatlar",
            },
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(
                        upload_to="receipts/%Y/%m/", verbose_name="Chek rasmi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="To'lov summasi"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Tasdiqlandi"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="cohorts.enrollment",
                        verbose_name="O'quvchi obunasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov cheki",
                "verbose_name_plural": "To'lov cheklari",
            },
        ),
    ]
