# Generated by Django 6.0.2 on 2026-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov davri tugashi"),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov davri boshlanishi"),
        ),
    ]
