# Generated by Django 6.0.2 on 2026-03-06 19:43

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_paymentreceipt_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_image',
            field=models.ImageField(upload_to='receipts/%Y/%m/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension], verbose_name='Chek rasmi'),
        ),
    ]
