# Generated by Django 6.0.2 on 2026-03-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_attendance_status_and_xp'),
        ('subscriptions', '0002_alter_plan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='subscriptions.plan', verbose_name='Tarif'),
        ),
    ]
