# Generated by Django 6.0.2 on 2026-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_enrollment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram chat ID'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='telegram_chat_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram chat nomi'),
        ),
    ]
