# Generated by Django 6.0.2 on 2026-04-11 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cohorts", "0007_alter_attendance_date"),
        ("courses", "0012_lessonprogress"),
        ("subscriptions", "0002_alter_plan_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="cohorts_att_date_3b32c4_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["enrollment", "date"], name="cohorts_att_enrollm_26d38f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="cohorts_enr_status_5fd7af_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="cohorts_enr_student_b6db73_idx"
            ),
        ),
    ]
