# Generated by Django 6.0.2 on 2026-04-19 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0008_attendance_cohorts_att_date_3b32c4_idx_and_more'),
        ('subscriptions', '0002_alter_plan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kurs tugallangan vaqt'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_state',
            field=models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Tugallangan'), ('promotion_ready', 'Keyingi bosqichga tayyor')], default='in_progress', max_length=20, verbose_name='Akademik holat'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='promotion_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Keyingi bosqichga tayyor vaqt'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['completion_state'], name='cohorts_enr_complet_c36daa_idx'),
        ),
    ]
