# Generated by Django 6.0.2 on 2026-04-19 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0009_enrollment_completed_at_enrollment_completion_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('promotion', 'Promotion'), ('transfer', 'Transfer')], max_length=16, verbose_name='Transition turi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('progress_items_moved', models.PositiveIntegerField(default=0, verbose_name="Ko'chirilgan progress soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollment_transitions', to=settings.AUTH_USER_MODEL, verbose_name='Amalni bajargan xodim')),
                ('source_cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='cohorts.cohort', verbose_name='Manba cohort')),
                ('source_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='cohorts.enrollment', verbose_name='Manba enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_transitions', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('target_cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='cohorts.cohort', verbose_name='Maqsad cohort')),
                ('target_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='cohorts.enrollment', verbose_name='Yangi enrollment')),
            ],
            options={
                'verbose_name': 'Enrollment transition',
                'verbose_name_plural': 'Enrollment transitions',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='cohorts_enr_student_091e64_idx'), models.Index(fields=['kind', 'created_at'], name='cohorts_enr_kind_7f499d_idx')],
            },
        ),
    ]
