# Generated by Django 6.0.2 on 2026-04-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0010_enrollmenttransition'),
        ('courses', '0015_course_certificate_min_attendance_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_checkout_default',
            field=models.BooleanField(default=False, help_text='Yangi checkout uchun aynan shu cohort birinchi tanlanadi.', verbose_name='Checkout default cohort'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('is_checkout_default', True)), fields=('course',), name='cohorts_one_checkout_default_per_course'),
        ),
    ]
