# Generated by Django 6.0.2 on 2026-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0011_cohort_is_checkout_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Asl summa'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma summasi'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='promo_campaign_snapshot',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Promo campaign'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='promo_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Promokod'),
        ),
    ]
