# Generated by Django 6.0.2 on 2026-08-15 01:07

import core.private_storage
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0012_paymentreceipt_base_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='receipt_image',
            field=models.ImageField(storage=core.private_storage.private_media_storage, upload_to='receipts/%Y/%m/', validators=[core.utils.validate_file_size, core.utils.validate_image_extension], verbose_name='Chek rasmi'),
        ),
    ]
