# Generated by Django 6.0.8 on 2026-08-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0013_alter_paymentreceipt_receipt_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('enrollment',), name='unique_pending_receipt_per_enrollment'),
        ),
    ]
