# Generated by Django 6.0.8 on 2026-08-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0014_paymentreceipt_unique_pending_receipt_per_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='checkout_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checkout boshlangan payt'),
        ),
    ]
