# Generated by Django 6.0.8 on 2026-09-04 02:04

import django.db.models.deletion
from django.db import migrations, models


def preserve_open_checkouts(apps, schema_editor):
    """Faqat ochiq niyatlar; tasdiqlangan tarixga hozirgi tarif taxmin qilinmaydi."""
    alias = schema_editor.connection.alias
    Enrollment = apps.get_model("cohorts", "Enrollment")
    Receipt = apps.get_model("cohorts", "PaymentReceipt")
    pending = Receipt.objects.using(alias).filter(is_verified=False).select_related("enrollment__plan")
    for receipt in pending.iterator():
        plan = receipt.enrollment.plan
        if plan is not None:
            Receipt.objects.using(alias).filter(pk=receipt.pk).update(
                plan_id=plan.pk, plan_code_snapshot=plan.code,
                plan_name_snapshot=plan.name,
                # Bu asl invoice summasi; bugungi katalog narxi emas.
                plan_price_snapshot=receipt.base_amount,
            )
            Enrollment.objects.using(alias).filter(pk=receipt.enrollment_id).update(pending_plan_id=plan.pk)

    intents = Enrollment.objects.using(alias).filter(
        checkout_started_at__isnull=False, pending_plan__isnull=True, plan__isnull=False,
    )
    for enrollment in intents.iterator():
        # Eski kod tasdiqdan keyin timestampni tozalamagan. Uni qayta to'lov
        # niyati deb qayta tiriltirmaymiz.
        completed = Receipt.objects.using(alias).filter(
            enrollment_id=enrollment.pk, is_verified=True,
            submitted_at__gte=enrollment.checkout_started_at,
        ).exists()
        if completed:
            Enrollment.objects.using(alias).filter(pk=enrollment.pk).update(checkout_started_at=None)
        else:
            Enrollment.objects.using(alias).filter(pk=enrollment.pk).update(pending_plan_id=enrollment.plan_id)


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0015_enrollment_checkout_started_at'),
        ('subscriptions', '0005_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_enrollments', to='subscriptions.plan', verbose_name='Tasdiq kutilayotgan tarif'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='subscriptions.plan', verbose_name='Sotib olinayotgan tarif'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='plan_code_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='plan_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='plan_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='plan_snapshot_source',
            field=models.CharField(choices=[('checkout', 'Checkout vaqtida'), ('legacy', 'Tarixiy yozuv')], default='legacy', editable=False, max_length=12),
        ),
        migrations.RunPython(preserve_open_checkouts, migrations.RunPython.noop),
    ]
