# Generated by Django 6.0.8 on 2026-09-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0016_payment_plan_snapshot'),
        ('courses', '0020_studentanswer_audio_key_and_more'),
        ('subscriptions', '0007_seed_delivery_catalog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cohort',
            name='cohorts_one_checkout_default_per_course',
        ),
        migrations.AddField(
            model_name='cohort',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Guruh sig'imi"),
        ),
        migrations.AddField(
            model_name='cohort',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cohorts', to='subscriptions.plan', verbose_name='Guruh tarifi'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('is_checkout_default', True), ('plan__isnull', True)), fields=('course',), name='cohorts_one_checkout_default_per_course'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(condition=models.Q(('is_checkout_default', True), ('plan__isnull', False)), fields=('course', 'plan'), name='cohorts_one_default_per_course_plan'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('capacity__isnull', True), ('plan__isnull', True)), models.Q(('capacity__gte', 1), ('capacity__isnull', False), ('plan__isnull', False)), _connector='OR'), name='cohorts_delivery_capacity_pair'),
        ),
    ]
