# Generated by Django 6.0.8 on 2026-09-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0017_remove_cohort_cohorts_one_checkout_default_per_course_and_more'),
        ('subscriptions', '0008_drop_seeded_group_size_feature'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentreceipt',
            name='unique_pending_receipt_per_enrollment',
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='kind',
            field=models.CharField(choices=[('period', "Davr uchun to'lov"), ('difference', 'Tarif farqi')], default='period', editable=False, max_length=12, verbose_name="To'lov turi"),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('enrollment', 'kind'), name='unique_pending_receipt_per_enrollment'),
        ),
    ]
