# Generated by Django 6.0.2 on 2026-03-19 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lessonprogress'),
        ('messenger', '0002_ailongtermmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRAGChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('chunk_text', models.TextField()),
                ('chunk_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(default='gemini-embedding-001', max_length=80)),
                ('embedding_dim', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'RAG Chunk',
                'verbose_name_plural': 'RAG Chunklar',
                'indexes': [models.Index(fields=['course', 'lesson'], name='messenger_l_course__489b77_idx'), models.Index(fields=['lesson', 'embedding_model'], name='messenger_l_lesson__c1b4e5_idx'), models.Index(fields=['updated_at'], name='messenger_l_updated_687c47_idx')],
                'unique_together': {('lesson', 'chunk_index', 'embedding_model')},
            },
        ),
    ]
