# Generated by Django 6.0.2 on 2026-04-11 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_lessonprogress_courses_les_enrollm_1a9f99_idx_and_more"),
        ("messenger", "0003_lessonragchunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at"], name="messenger_m_created_fdc358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created_at"], name="messenger_m_room_id_7234a8_idx"
            ),
        ),
    ]
