# Generated by Django 6.0.2 on 2026-04-19 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_aifeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='comment',
            field=models.TextField(blank=True, default='', help_text="Qo'shimcha izoh"),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='messenger.message'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='aifeedback',
            unique_together={('message', 'student')},
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['rating', 'created_at'], name='messenger_a_rating_d09c23_idx'),
        ),
        migrations.AddIndex(
            model_name='aifeedback',
            index=models.Index(fields=['student', 'created_at'], name='messenger_a_student_3856cd_idx'),
        ),
    ]
