# Generated by Django 6.0.2 on 2026-05-23 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_aifeedback_updated_at_alter_aifeedback_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('preference', 'Preference'), ('learning_goal', 'Learning goal'), ('weak_topic', 'Weak topic'), ('schedule', 'Schedule'), ('profile', 'Profile'), ('do_not_remember', 'Do not remember'), ('other', 'Other')], default='other', max_length=32)),
                ('key', models.CharField(blank=True, default='', max_length=120)),
                ('value', models.TextField()),
                ('confidence', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='active', max_length=16)),
                ('visibility', models.CharField(choices=[('user_visible', 'User visible'), ('internal', 'Internal')], default='user_visible', max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_memory_facts', to='messenger.message')),
                ('source_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_memory_facts', to='messenger.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Memory Fact',
                'verbose_name_plural': 'AI Memory Facts',
                'indexes': [models.Index(fields=['user', 'status', 'category'], name='messenger_a_user_id_bc6c88_idx'), models.Index(fields=['user', 'updated_at'], name='messenger_a_user_id_71fffe_idx'), models.Index(fields=['fingerprint'], name='messenger_a_fingerp_ec3585_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'fingerprint'), name='unique_ai_memory_fact_fingerprint')],
            },
        ),
    ]
