# Generated by Django 6.0.2 on 2026-05-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_aimemoryfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('covered_message_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('covered_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_by_ai_summaries', to='messenger.message')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_summary', to='messenger.chatroom')),
            ],
            options={
                'verbose_name': 'AI Conversation Summary',
                'verbose_name_plural': 'AI Conversation Summaries',
                'indexes': [models.Index(fields=['updated_at'], name='messenger_a_updated_1f3d01_idx')],
            },
        ),
    ]
