# Generated by Django 6.0.2 on 2026-05-23 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_aiconversationsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemoryTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('retrieved', 'Retrieved'), ('saved', 'Saved'), ('skipped', 'Skipped'), ('archived', 'Archived')], max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Memory Trace',
                'verbose_name_plural': 'AI Memory Traces',
            },
        ),
        migrations.AddField(
            model_name='aimemoryfact',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aimemoryfact',
            name='embedding_dim',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimemoryfact',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='aimemoryfact',
            index=models.Index(fields=['user', 'embedding_model'], name='messenger_a_user_id_295add_idx'),
        ),
        migrations.AddField(
            model_name='aimemorytrace',
            name='fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_events', to='messenger.aimemoryfact'),
        ),
        migrations.AddField(
            model_name='aimemorytrace',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_memory_traces', to='messenger.chatroom'),
        ),
        migrations.AddField(
            model_name='aimemorytrace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory_traces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aimemorytrace',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='messenger_a_user_id_21f65f_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemorytrace',
            index=models.Index(fields=['fact', 'created_at'], name='messenger_a_fact_id_bb08ad_idx'),
        ),
    ]
