# Generated by Django 6.0.2 on 2026-05-23 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_readingitem_readingacceptedanswer_readingpassage_and_more'),
        ('messenger', '0009_aimemorytrace_aimemoryfact_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message_id', models.CharField(blank=True, default='', max_length=80)),
                ('user_question', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('fallback', 'Fallback'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('skill_slug', models.CharField(blank=True, default='', max_length=80)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_runs', to='messenger.message')),
                ('context_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_runs', to='messenger.chatroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_response_runs', to=settings.AUTH_USER_MODEL)),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_response_runs', to='messenger.message')),
            ],
            options={
                'verbose_name': 'AI Response Run',
                'verbose_name_plural': 'AI Response Runs',
                'indexes': [models.Index(fields=['room', 'created_at'], name='messenger_a_room_id_df00ce_idx'), models.Index(fields=['student', 'status', 'created_at'], name='messenger_a_student_148365_idx'), models.Index(fields=['user_message', 'status'], name='messenger_a_user_me_d3a868_idx')],
            },
        ),
    ]
