# Generated by Django 6.0.2 on 2026-05-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_readingitem_readingacceptedanswer_readingpassage_and_more'),
        ('messenger', '0010_airesponserun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat room user state',
                'verbose_name_plural': 'Chat room user states',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messenger/attachments/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'is_deleted', 'created_at'], name='messenger_m_room_id_65df6b_idx'),
        ),
        migrations.AddField(
            model_name='chatroomuserstate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='messenger.chatroom'),
        ),
        migrations.AddField(
            model_name='chatroomuserstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatroomuserstate',
            index=models.Index(fields=['user', 'is_pinned', 'updated_at'], name='messenger_c_user_id_d99279_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroomuserstate',
            index=models.Index(fields=['room', 'user'], name='messenger_c_room_id_bfcc82_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroomuserstate',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_chat_room_user_state'),
        ),
    ]
