# Generated by Django 6.0.2 on 2026-07-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_chatroomuserstate_message_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFormSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(help_text="Registry name of the form (e.g. 'user_onboarding')", max_length=120)),
                ('state', models.JSONField(blank=True, default=dict, help_text='Unified state (fields, values, status)')),
                ('status', models.CharField(choices=[('created', 'Created'), ('collecting', 'Collecting'), ('validating', 'Validating'), ('ready', 'Ready'), ('submitting', 'Submitting'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_form_sessions', to='messenger.chatroom')),
            ],
            options={
                'verbose_name': 'Smart Form Session',
                'verbose_name_plural': 'Smart Form Sessions',
                'indexes': [models.Index(fields=['status', 'created_at'], name='messenger_s_status_8f6f4d_idx'), models.Index(fields=['chat_room', 'status'], name='messenger_s_chat_ro_d61b8a_idx')],
            },
        ),
    ]
