# Generated by Django 6.0.2 on 2026-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_smartformsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponserun',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airesponserun',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airesponserun',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
