# Generated by Django 6.0.2 on 2026-08-13 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_question_max_word_count_question_min_word_count_and_more'),
        ('messenger', '0013_airesponserun_completion_tokens_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airesponserun',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddConstraint(
            model_name='airesponserun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_ai_run_idempotency_key'),
        ),
    ]
