# Generated by Django 6.0.2 on 2026-08-15 01:07

import core.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0014_ai_response_idempotency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=core.private_storage.private_media_storage, upload_to='messenger/attachments/%Y/%m/%d'),
        ),
    ]
