# Generated by Django 6.0.8 on 2026-09-09 23:21

import core.private_storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Faqat FK qilinayotgan jadvallar yaratilgan nuqtalarga bog'lanamiz.
        # Latest leaf'larni ko'rsatish eski cohort/subscription sxemasidan
        # upgrade qiladigan migration-regressiya testlarini qarama-qarshi
        # targetlarga majbur qilardi.
        ('bot', '0001_initial'),
        ('cohorts', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('single_choice', 'Bitta javobli tanlov'), ('multiple_choice', 'Bir nechta javobli tanlov'), ('true_false', "To'g'ri / noto'g'ri"), ('short_answer', 'Qisqa javob'), ('fill_blank', "Bo'sh joyni to'ldirish"), ('matching', 'Juftliklarni moslashtirish'), ('ordering', 'Tartiblash'), ('categorization', 'Kategoriyalarga ajratish'), ('unscramble', "So'z/gapni yig'ish"), ('poll', 'Poll — baholanmaydi')], db_index=True, max_length=32)),
                ('prompt', models.TextField()),
                ('instructions', models.CharField(blank=True, default='', max_length=500)),
                ('config', models.JSONField(default=dict)),
                ('answer_key', models.JSONField(default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('media', models.FileField(blank=True, null=True, storage=core.private_storage.private_media_storage, upload_to='classbook/exercises/%Y/%m/')),
                ('media_kind', models.CharField(blank=True, choices=[('image', 'Rasm'), ('audio', 'Audio')], default='', max_length=10)),
                ('media_content_type', models.CharField(blank=True, default='', max_length=120)),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)])),
                ('max_points', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('speed_bonus_percent', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('is_active', models.BooleanField(default=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classbook_exercises', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classbook_exercises', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classbook_exercises', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Classbook mashqi',
                'verbose_name_plural': 'Classbook mashqlari',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('ready', 'Darsga tayyor')], db_index=True, default='draft', max_length=10)),
                ('opening_message', models.TextField(blank=True, default='')),
                ('materials_message', models.TextField(blank=True, default='')),
                ('homework_message', models.TextField(blank=True, default='')),
                ('late_after_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(180)])),
                ('auto_release_lesson', models.BooleanField(default=True)),
                ('announce_names', models.BooleanField(default=False, help_text="O'chirilgan holatda guruhga faqat umumiy sonlar yuboriladi.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classbook_playbooks', to='cohorts.cohort')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classbook_playbooks', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classbook_playbooks', to='courses.lesson')),
            ],
            options={
                'verbose_name': "Dars playbook'i",
                'verbose_name_plural': "Dars playbook'lari",
                'ordering': ['cohort__name', 'lesson__module__order', 'lesson__order'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('teacher_note', models.CharField(blank=True, default='', max_length=500)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playbook_steps', to='classbook.exercise')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_steps', to='classbook.lessonplaybook')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Navbatda'), ('open', 'Ochiq'), ('closed', 'Yopilgan'), ('revealed', "Natija e'lon qilingan")], db_index=True, default='queued', max_length=12)),
                ('snapshot', models.JSONField(default=dict)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_classbook_activities', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classbook_activities', to='bot.telegramlessonsession')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='classbook.exercise')),
                ('playbook_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='classbook.playbookexercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('accuracy', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('speed_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_correct', models.BooleanField(default=False)),
                ('grading_details', models.JSONField(default=dict)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='classbook.activityrun')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classbook_responses', to='cohorts.enrollment')),
            ],
            options={
                'ordering': ['-score', 'response_ms', 'submitted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TelegramGroupDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=160, unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('attendance', 'Davomat tugmasi'), ('link', 'Classbook havolasi'), ('text', 'Oddiy xabar')], default='text', max_length=12)),
                ('text', models.TextField()),
                ('button_text', models.CharField(blank=True, default='', max_length=80)),
                ('button_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('claim_token', models.CharField(blank=True, default='', max_length=32)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_deliveries', to='classbook.activityrun')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classbook_group_deliveries', to='bot.telegramlessonsession')),
            ],
            options={
                'verbose_name': 'Classbook Telegram xabari',
                'verbose_name_plural': 'Classbook Telegram xabarlari',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['course', 'kind', 'is_active'], name='classbook_e_course__fa1ca3_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonplaybook',
            constraint=models.UniqueConstraint(fields=('cohort', 'lesson'), name='classbook_unique_playbook'),
        ),
        migrations.AddConstraint(
            model_name='playbookexercise',
            constraint=models.UniqueConstraint(fields=('playbook', 'order'), name='classbook_unique_playbook_step_order'),
        ),
        migrations.AddIndex(
            model_name='activityrun',
            index=models.Index(fields=['session', 'status', 'order'], name='classbook_a_session_588009_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityrun',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='classbook_unique_session_activity_order'),
        ),
        migrations.AddConstraint(
            model_name='activityrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('session',), name='classbook_one_open_activity_per_session'),
        ),
        migrations.AddIndex(
            model_name='studentresponse',
            index=models.Index(fields=['activity', '-score', 'response_ms'], name='classbook_s_activit_03db9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.UniqueConstraint(fields=('activity', 'enrollment'), name='classbook_one_response_per_activity'),
        ),
        migrations.AddIndex(
            model_name='telegramgroupdelivery',
            index=models.Index(fields=['status', 'id'], name='classbook_t_status_21e2e9_idx'),
        ),
    ]
