# Generated by Django 6.0.8 on 2026-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbook', '0002_telegramgroupdelivery_failure_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='creation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='edit_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='lessonplaybook',
            name='edit_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
