# Generated by Django 6.0.2 on 2026-02-22 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Yutuq nomi")),
                (
                    "description",
                    models.TextField(verbose_name="Ta'rifi (Qanday olinadi?)"),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="badges/", verbose_name="Yutuq rasmi (Ikonka)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nishon (Badge)",
                "verbose_name_plural": "Nishonlar",
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Daraja nomi")),
                (
                    "min_xp",
                    models.PositiveIntegerField(
                        verbose_name="Minimal XP (Shu darajaga o'tish uchun)"
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="levels/",
                        verbose_name="Daraja nishoni (Rasm)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daraja (Level)",
                "verbose_name_plural": "Darajalar",
                "ordering": ["min_xp"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Sertifikat ID",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Berilgan sana"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="Sertifikat fayli (PDF/Rasm)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.course",
                        verbose_name="Tugatgan kursi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'quvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifikat",
                "verbose_name_plural": "Sertifikatlar",
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="EarnedBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Olingan vaqti"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.badge",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Olingan nishon",
                "verbose_name_plural": "Olingan nishonlar",
                "unique_together": {("student", "badge")},
            },
        ),
    ]
