# Generated by Django 6.0.2 on 2026-03-02 00:02

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Ta'rifi (Qanday olinadi?)"),
        ),
    ]
