# Generated by Django 6.0.2 on 2026-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_badge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='google_icon_name',
            field=models.CharField(blank=True, default='', help_text='Masalan: workspace_premium, military_tech, school.', max_length=80, verbose_name='Google icon nomi'),
        ),
        migrations.AddField(
            model_name='badge',
            name='google_icon_style',
            field=models.CharField(choices=[('outlined', 'Outlined'), ('rounded', 'Rounded'), ('sharp', 'Sharp')], default='outlined', max_length=12, verbose_name='Google icon uslubi'),
        ),
        migrations.AddField(
            model_name='badge',
            name='icon_source',
            field=models.CharField(choices=[('upload', 'Rasm yuklash'), ('google', 'Google Icon')], default='upload', max_length=12, verbose_name='Ikonka manbasi'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/', verbose_name='Yutuq rasmi (Ikonka)'),
        ),
    ]
